; HEADER_BLOCK_START
; generated by OrcaSlicer 1.5.0 on 2023-07-09 at 11:51:00
; estimated printing time (normal mode) = 3m 40s
; total layer number: 25
; HEADER_BLOCK_END

; hack-fix: write fake slicer info here so that preprocess_cancellation can process.
; generated by SuperSlicer 1.5.0 on 2023-07-09 at 11:51:00

; THUMBNAIL_BLOCK_START
; thumbnail begin 300x300 5420
; iVBORw0KGgoAAAANSUhEUgAAASwAAAEsCAYAAAB5fY51AAAPp0lEQVR4Ae3dy5IcVxWF4XoVC2ywsE
; 1IJdmWAMMUEbK4B5gJI3MRAQQ3cwlDOXgIMBMbA8/CY5UrW52hUqkumXn2Pmevs//BN3UvZZ38u5Rq
; d63W6/UKABRIjQWQm9RYALlJjQWQm9RYALlJjQWQm9RYALlJjQWQm9RYALlJjQWQm9RYALlJjQWQm9
; RYALlJjQWQm9RYALlJjQWQm9RYALlJjQWQm9RYALlJjQWQm9RYALlJjQWQm9RYALlJjQWQm9RYALlJ
; jQWQm9RYALlJjQWQm9RYALlJjQWQm9RYALlJjQWQm9RYALlJjQWQm9RYALlJjQWQm9RYALlJjQWQm9
; RYALlJjQWQm9RYALlJjQWQm9RYALlJjQWQm9RYALlJjQWQm9RYALlJjQWQm9RYALlJjQWQm9RYALlJ
; jQWQm9RYALlJjQWQm9RYALlJjQWQm9RYALlJjQWQm9RYALlJjQWQm9RYALlJjQWQm9RYALlJjQWQm9
; RYALlJjQWQm9RYALlJjQWQm9RYALlJjQWQm9RYALlJjQWQm9RYALlJjQWQm9TYSN5/cH9zidKfB1Ag
; NbaVMUD///HXtksQMMCG1NjalgaKeAE+pMbWUPJOakm8lK4N0JrUWG+1QkW4gGWkxnppFSqiBcwjNd
; ZDhFgRLWAaqbHWIsWKcAGXSY21FDVWBAs4TWqslZr/Eki0ADtSY61EjxXRAo6TGmtBJVYEC3ie1FgL
; SsEiWsCzpMaWUnh2RbCA06TGllIK1T6lawx4khpbSilSBGse3onmIDW2lFKkCNb815Vo9U9qbCmlSB
; GsZa8p0eqb1NhSKoEiWOWvJeHqk9TYUv95dFciUATrvKnXjWj1R2psKcVg/fPBLYJ1bcmPpfAbXvsi
; NbbUB1+9GT5Qhx7fuUGw1uV/nSdafZAaW2oI1v++qfMu68PduyuCZffskWjpkxpbagjW34Wi9fjOZ1
; IHy+u6Ei5dUmNLKQXrF1exyhss7+tLtDRJjS01Bit6tIZYZQ1W7f/fk3BpkRpbaj9YUaP1+DpWGYPV
; 6poTLR1SY0sdBmvw30A/6vD4OlLZghXht2jw4w8apMaWOhasD966ud289fK29c9oDWHKGKzWoToWLq
; Xrl43U2FLngvW3nU920frk7TtVb5CfrW9sf76+kTJYUSJFtHRIjS11KVh//crL2/e//Pntv3fR+tg5
; XP/4+q2rWGUMVrRAES4dUmNLTQ3WX3b+/KXPbT9+eOeKZaTevfXC9ie3X9j+dCdjsCKGiWjpkBpbam
; 6w/nT/iT9e+2gXr48erq9cOuj/+sbt7YcPbl/9tPoQpSFS7w6SBkvx11PvR4twxSA1tlRpsAbv3X9p
; +969l7Z/2Pn9zu/efHH722u/eePF7a9f/+z2Vzu/vDtG50b6YCnFiXdbsUmNLUWw6lMKEtGKT2psKY
; JVj1KECJcOqbGlCFYdSuEhWlqkxpYiWL6UH6yXRItw1SM1thTB8qMUGd5t6ZIaW4pg+Xjn3msb1d+X
; b2V4DaO/Tj2QGluKYPkYgjVcwwj/T2aLUI2iv049kBpbimD52A9Wpmjtx4pg1SE1thTB8nEYrDFavY
; Zr+CSjw1gRrDqkxpYiWD6OBavXd1vHQkWw6pEaW4pg+TgXrJ6idS5WBKsOqbGlCJaPS8FSD9elUBGs
; eqTGliJYPqYGSzFaU2NFsOqQGluKYPmYEyyVcJ16sE6w2pIaW4pg+VgSrMjRmhsqglWP1NhSBMvH0m
; BF+/GHJe+qCFZdUmNLESwfJcGK8m6rJFQEqx6psaV+dO+LG4JlzyJYLaNlESuCVYfU2FKKwXp05wub
; 6NfVKli1w2UVKoJVj9TYUorBUriu1sGqES3rWBGsOqTGWjiMFsEq5xEsrwfypQ/WCVZbUmMtKAVL5Z
; p6Bcv63ZZXqAhWPVJjrexHi2CV8w6WRbS8Y0Ww6pAaa2mMVtRgKV3LGsFaGq4aoYoerPFa9PBrnKXG
; WhuiFTFYStdwUDNYc6JVM1ZRg3V4TdQ/NENqrId3dtGKFCyla/f0GtYN1hitU+HyfLCuEqxLn2CkGi
; 2psV6GGy5CsJSu2eH1qx2sU++2WoQqWrCm/nVZMVpSYz398M3XNj/YaREspet0TMtg7b/bahmrKMFa
; 8g8SSuGSGFnTEK1awXp7Xf5T7BEOXetgDYbXInOwSn/kQyVa4Qe28v03Xt0MPIL1cH1zY7ExyqEjWG
; 2DVRorpXCFHRbJGK+lwRreSVlFanDpwNU+dASrTbAuPVjvMVohR0X3vddf3Qy+e+WVzXcGd1/ZfHvn
; W9e8vnbEQ0ew6gfLI1Stv/FNEWoMTlvy3bTWoSNYdYPlHavI77bCDMFp0Q8dwaoTrJqhihqtECNwms
; KhI1j+wWoVq2jhWrUegOOUDh3B8gtWhFBFitaq5RfHcWqHjmD5BCtSqA7PT6twrVp8UbQ/oJaHbghW
; 62i1Dtajtd2vsvb6cYXo3/imWNX+gjiuh0PXMlotg9XDOVCJ1qrmF8PzInw37SFarYJleRYiBCjCGT
; pnVeOLQOOAKoerdrB6PgcRzs8pK+8vAK1DqhqtmsHKcA5Kzo9nuFxvSmgeUOtDVyNcNYKV8cF6yRny
; uH/cb1A8pXTgrA+dd7S8g5X5HJScH+twud+k0P5uah0tr3B5BcvyXdVA6bWPeIbcb9bslA5WzXApBI
; tzEO/8VLlps1I6UDUP3cA6WtbB4hzYsrqm1W7eTJQOUi/hsgqW5Tno/cH6FPufYGRxTavdxFkoHaae
; omURLM6BLY/rW+1G7p3SQbKMVpT/H7EkWPy4gj2vbwjVbuieKR0kDxHebS0NFufAlve1rnZT92q4wa
; Z+dHqvrP/pf0m0lgTLcrPS6+WlxvWuclP3bLy5zn10eu8H1DpYh9fWOliWG5VeLy/7D9YJVnCHN1WW
; aHk9A7p0fUuDZblN6fWqcQ4IloBjN1TP77aOfTf1DNZ4jS+F61KweLBur8Vfwd1v6N6du5F6i1aNGC
; y91ueCZblB6fXyMjdUBCuQS9/5e4jWpWcUtYI1Xu9j1/xUsCy/ttJr5mVprAhWEFOfsaiGa8pBrBms
; U9f9MFiWX0vp9Wp5DgiWgDn/kqUWrakHsUWwDq/9frAsv4bS69X6HBAsAXN/Zkjhgfzcg9gqWPuvwR
; Asy/8mD9an/7gCwRKy9Cezo0ZryUFsHSxrEV8XhXNAsASU/P9vkaJV8t20p2BFeT1a8ogVwQrC4jcN
; tA5X6UHsIVgRQtGaV6gIViBWv8+pVbQsDqJ6sKIEoyXvWBGsICx/c2bNB/KWB1E1WJGC0Yr1g3WCFZ
; zH7yf3jpb1QVQMVrRwtFArVAQrEK9PgfGIltd3U6Vg8eMKbWJFsILw/rw9q3B5HkSVYEWNR00tQkWw
; Aqnxqcal0fI+iArBihqQmlrGimAFUSNYS8NV6yBGDlb0iNRQ88E6wQquZrDmRKvmQYwarOghqSFCqA
; hWILWDNUbrVLhaHMRoweLBepx3VQQrmBbBOvVuq9VBjBQslaB4ihAnghVUy2CN0Wr93TRKsJSiki1W
; BCuI1sEatD6IrYOlFJSMoSJYgRCstsFSikrmWBEsgpU6WDxYj/lgnWARLIJ1QCkqXiIEiGARLIJ1Bu
; +qdGNFsAhWqmApBYVQ2YeKYBEsmWApRYVY+cWKYBGs0MFSCooXtQfr3meiyU1OsAgWsbosQniW8Lzf
; mtzkvQWrdbR6OqA8WNd9V+UdK4JlHK6MwbK8hkpR8RIhOhFDRbActIpWD4dUKSqKsRo+GVvhHFzS5M
; buXe1weR1EQqUfqvGMeASrxb21avFFM6gZLc8DT6z0Y+URrFb31arVF86g1gN5z0PvcUB5sO77YH2I
; 0+EZsQpW69/MsWr5xbPwjpZnqKxjpRQVL56v1akzYhGsCPdS8wFZeEbL6/BbfjflXVW7WFkEK8p9FG
; JEJh7h8jj8ln9mpaD0FqrSYEW7f0KNycI6WpFjNTj3oRkZtI7V0mBFvHfCDcrC8oF81FCNxp3ZouX5
; YH346/qc8zMnWJE/ZzLkqEwsohU5VoP9rVmi5RWqw9dq6je+qcGKdG8cE3pcFqXRKv1O7f3nO7a553
; DVitWcMzQlWBHuhUvCD8xkabisD7+1U7t7i1aLUE09P+eC1frczyEzNIsl0Yocq8G57b08kG8dq0tn
; 6FSwWp3zpaTGZjInXFFDNZryZ1CNlmeoSv66fnh+DoMV+cH6OVJjs5karcixGkwNr1q0Ir2rOnV+xj
; O0H6xW58CC1NiMpvwrUNRQjeb+FTd6uLx/XMHjDA3BUn1XtU9qbGbnohU5VoO5wYocrejvqnonNTa7
; U9Gq9Z16qSXBivhAnli1JzUWTxyGK/rhXxqsKO+2CFUcUmPx1H60ot8ApcFqGS1iFYvUWDxrfCAf/f
; BbBKt2uNQerGchNRaaLINVI1q8q4pLaiw0WQfLM1zEKjapsdDkFSzLaHmGiljZkRoLTZ7BGqNVEi7v
; WBEsO1Jjock7WEvfbdX8SHil1ysyqbHQVCtYc6JVK1QEy5bUWGiqGaxL4ar5ropg2ZMaC00tgnUsWi
; 1CRbBsSY2FplbBGqM1aBkrgmVHaiw0tQzWwOpj2glWe1JjoYlgESwrUmOhiWARLCtSY6GJYBEsK1Jj
; oYlgESwrUmOhiWARLCtSY6GJYBEsK1JjoYlgESwrUmOhiWARLCtSY6FpzqdYEyycIzUWulpGq2WwlF
; 4jBVJjoW3Kp1j3FCyl10aF1Fj0oXa0ageLT8XxIzUW/agZrZrBUnoNFEmNRX9qhKtGsHhXVYfUWPTJ
; O1rewVK61uqkxqJfng/kPYOldI17IDUW/fOIlkewlK5pT6TGIgfraFkHS+la9kZqLHKxCpdVsHiw3p
; 7UWORjES2LYClds55JjUVeJeEqDZbSdeqd1FjktjRaS4OldG2ykBoLLPnxhyXBUrommUiNBUZzojUn
; WDxYj01qLLBvarSmBkvpz56V1FjgmEvhuhQs3lXpkBoLnHIuWueCpfRnBMFCR049kD8VLKU/G56QGg
; tMcRitw2Ap/VnwLKmxwFT70doPltKfAc+TGgvMNYRrCBYP1vsgNRZAblJjAeQmNRZAblJjAeQmNRZA
; blJjAeQmNRZAblJjAeQmNRZAblJjAeQmNRZAblJjAeQmNRZAblJjAeQmNRZAblJjAeQmNRZAblJjAe
; QmNRZAblJjAeQmNRZAblJjAeQmNRZAblJjAeQmNRZAblJjAeQmNRZAblJjAeQmNRZAblJjAeQmNRZA
; blJjAeQmNRZAblJjAeQmNRZAblJjAeQmNRZAblJjAeQmNRZAblJjAeQmNRZAblJjAeQmNRZAblJjAe
; QmNRZAbp8Cvk44TOQMavUAAAAASUVORK5CYII=
; thumbnail end
; THUMBNAIL_BLOCK_END
; ---- body elided for the test fixture ----

; CONFIG_BLOCK_START
; accel_to_decel_enable = 0
; accel_to_decel_factor = 50%
; additional_cooling_fan_speed = 0
; auxiliary_fan = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_exclude_area = 0x0
; bed_temperature_difference = 10
; before_layer_change_gcode = ;BEFORE_LAYER_CHANGE\n;[layer_z]\nG92 E0\n
; bottom_shell_layers = 3
; bottom_shell_thickness = 0
; bottom_solid_infill_flow_ratio = 1
; bottom_surface_pattern = monotonic
; bridge_acceleration = 50%
; bridge_angle = 0
; bridge_density = 100%
; bridge_flow = 0.95
; bridge_no_support = 0
; bridge_speed = 50
; brim_object_gap = 0.1
; brim_type = auto_brim
; brim_width = 5
; chamber_temperature = 0
; change_filament_gcode = 
; close_fan_the_first_x_layers = 3
; cool_plate_temp = 105
; cool_plate_temp_initial_layer = 105
; curr_bed_type = High Temp Plate
; default_acceleration = 5000
; default_filament_colour = ""
; default_filament_profile = "My Generic ABS"
; default_jerk = 0
; default_print_profile = 0.20mm Standard @MyKlipper
; deretraction_speed = 30
; detect_narrow_internal_solid_infill = 1
; detect_overhang_wall = 1
; detect_thin_wall = 0
; draft_shield = disabled
; elefant_foot_compensation = 0
; enable_arc_fitting = 0
; enable_overhang_bridge_fan = 1
; enable_overhang_speed = 1
; enable_pressure_advance = 0
; enable_prime_tower = 0
; enable_support = 0
; enforce_support_layers = 0
; eng_plate_temp = 105
; eng_plate_temp_initial_layer = 105
; ensure_vertical_shell_thickness = 1
; extruder_clearance_height_to_lid = 140
; extruder_clearance_height_to_rod = 36
; extruder_clearance_max_radius = 68
; extruder_clearance_radius = 65
; extruder_colour = #FCE94F
; extruder_offset = 0x0
; fan_cooling_layer_time = 30
; fan_max_speed = 80
; fan_min_speed = 10
; filament_colour = #F2754E
; filament_cost = 20
; filament_density = 1.04
; filament_diameter = 1.75
; filament_end_gcode = "; filament end gcode \n"
; filament_flow_ratio = 0.926
; filament_ids = GFB99
; filament_is_support = 0
; filament_max_volumetric_speed = 12
; filament_minimal_purge_on_wipe_tower = 15
; filament_settings_id = "My Generic ABS"
; filament_shrink = 100%
; filament_soluble = 0
; filament_start_gcode = "; Filament gcode\n"
; filament_type = ABS
; filament_vendor = Generic
; filename_format = {input_filename_base}_{filament_type[0]}_{print_time}.gcode
; filter_out_gap_fill = 0
; flush_into_infill = 0
; flush_into_objects = 0
; flush_into_support = 1
; flush_multiplier = 1
; flush_volumes_matrix = 0
; flush_volumes_vector = 140,140
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_point_distance = 0.8
; fuzzy_skin_thickness = 0.3
; gap_infill_speed = 100
; gcode_add_line_number = 0
; gcode_comments = 0
; gcode_flavor = klipper
; gcode_label_objects = 1
; host_type = octoprint
; hot_plate_temp = 105
; hot_plate_temp_initial_layer = 105
; independent_support_layer_height = 1
; infill_combination = 0
; infill_direction = 45
; infill_jerk = 9
; infill_wall_overlap = 25%
; initial_layer_acceleration = 500
; initial_layer_infill_speed = 105
; initial_layer_jerk = 9
; initial_layer_line_width = 0.5
; initial_layer_print_height = 0.2
; initial_layer_speed = 50
; initial_layer_travel_speed = 100%
; inner_wall_acceleration = 5000
; inner_wall_jerk = 9
; inner_wall_line_width = 0.45
; inner_wall_speed = 200
; interface_shells = 0
; internal_bridge_support_thickness = 0
; internal_solid_infill_acceleration = 100%
; internal_solid_infill_line_width = 0.4
; internal_solid_infill_speed = 200
; ironing_flow = 10%
; ironing_spacing = 0.15
; ironing_speed = 30
; ironing_type = no ironing
; layer_change_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.2
; line_width = 0.4
; machine_end_gcode = PRINT_END
; machine_load_filament_time = 0
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 20000,20000
; machine_max_acceleration_retracting = 5000,5000
; machine_max_acceleration_travel = 9000,9000
; machine_max_acceleration_x = 20000,20000
; machine_max_acceleration_y = 20000,20000
; machine_max_acceleration_z = 500,200
; machine_max_jerk_e = 2.5,2.5
; machine_max_jerk_x = 9,9
; machine_max_jerk_y = 9,9
; machine_max_jerk_z = 0.2,0.4
; machine_max_speed_e = 25,25
; machine_max_speed_x = 500,200
; machine_max_speed_y = 500,200
; machine_max_speed_z = 12,12
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; machine_pause_gcode = PAUSE
; machine_start_gcode = M190 S[bed_temperature_initial_layer_single]\nM109 S[nozzle_temperature_initial_layer]\nPRINT_START EXTRUDER=[nozzle_temperature_initial_layer] BED=[bed_temperature_initial_layer_single]\n
; machine_unload_filament_time = 0
; max_bridge_length = 10
; max_layer_height = 0.32
; max_travel_detour_distance = 0
; min_bead_width = 85%
; min_feature_size = 25%
; min_layer_height = 0.08
; minimum_sparse_infill_area = 15
; nozzle_diameter = 0.4
; nozzle_hrc = 0
; nozzle_temperature = 260
; nozzle_temperature_initial_layer = 260
; nozzle_temperature_range_high = 270
; nozzle_temperature_range_low = 240
; nozzle_type = undefine
; nozzle_volume = 0
; only_one_wall_first_layer = 0
; only_one_wall_top = 0
; ooze_prevention = 0
; outer_wall_acceleration = 3000
; outer_wall_jerk = 9
; outer_wall_line_width = 0.4
; outer_wall_speed = 120
; overhang_1_4_speed = 0
; overhang_2_4_speed = 50
; overhang_3_4_speed = 30
; overhang_4_4_speed = 10
; overhang_fan_speed = 80
; overhang_fan_threshold = 25%
; overhang_speed_classic = 0
; post_process = 
; precise_outer_wall = 0
; pressure_advance = 0.02
; prime_tower_brim_width = 3
; prime_tower_width = 35
; prime_volume = 45
; print_compatible_printers = "MyKlipper 0.4 nozzle"
; print_flow_ratio = 1
; print_host = 
; print_host_webui = 
; print_sequence = by layer
; print_settings_id = 0.20mm Standard @MyKlipper
; printable_area = 0x0,250x0,250x250,0x250
; printable_height = 250
; printer_model = Generic Klipper Printer
; printer_settings_id = MyKlipper 0.4 nozzle
; printer_technology = FFF
; printer_variant = 0.4
; printhost_apikey = 
; printhost_authorization_type = key
; printhost_cafile = 
; printhost_password = 
; printhost_port = 
; printhost_ssl_ignore_revoke = 0
; printhost_user = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 2
; raft_layers = 0
; reduce_crossing_wall = 0
; reduce_fan_stop_start_freq = 1
; reduce_infill_retraction = 1
; required_nozzle_HRC = 0
; resolution = 0.012
; retract_before_wipe = 70%
; retract_length_toolchange = 2
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_when_changing_layer = 1
; retraction_length = 0.8
; retraction_minimum_travel = 1
; retraction_speed = 30
; role_based_wipe_speed = 1
; scan_first_layer = 0
; seam_gap = 15%
; seam_position = aligned
; silent_mode = 0
; single_extruder_multi_material = 1
; skirt_distance = 2
; skirt_height = 1
; skirt_loops = 0
; slice_closing_radius = 0.049
; slicing_mode = regular
; slow_down_for_layer_cooling = 1
; slow_down_layer_time = 3
; slow_down_min_speed = 10
; small_perimeter_speed = 50%
; small_perimeter_threshold = 0
; solid_infill_filament = 1
; sparse_infill_acceleration = 100%
; sparse_infill_density = 15%
; sparse_infill_filament = 1
; sparse_infill_line_width = 0.45
; sparse_infill_pattern = grid
; sparse_infill_speed = 200
; spiral_mode = 0
; standby_temperature_delta = -5
; start_end_points = 30x-3,54x245
; support_angle = 0
; support_base_pattern = rectilinear
; support_base_pattern_spacing = 2.5
; support_bottom_interface_spacing = 0.5
; support_bottom_z_distance = 0.2
; support_critical_regions_only = 0
; support_expansion = 0
; support_filament = 0
; support_interface_bottom_layers = 2
; support_interface_filament = 0
; support_interface_loop_pattern = 0
; support_interface_pattern = rectilinear
; support_interface_spacing = 0.5
; support_interface_speed = 80
; support_interface_top_layers = 2
; support_line_width = 0.4
; support_object_xy_distance = 0.35
; support_on_build_plate_only = 0
; support_speed = 150
; support_style = default
; support_threshold_angle = 30
; support_top_z_distance = 0.2
; support_type = normal(auto)
; temperature_vitrification = 110
; template_custom_gcode = 
; textured_plate_temp = 105
; textured_plate_temp_initial_layer = 105
; thick_bridges = 0
; thumbnails = 300x300
; timelapse_type = 0
; top_shell_layers = 4
; top_shell_thickness = 0.8
; top_solid_infill_flow_ratio = 1
; top_surface_acceleration = 3000
; top_surface_jerk = 9
; top_surface_line_width = 0.4
; top_surface_pattern = monotonic
; top_surface_speed = 100
; travel_acceleration = 7000
; travel_jerk = 12
; travel_speed = 350
; travel_speed_z = 0
; tree_support_adaptive_layer_height = 1
; tree_support_auto_brim = 1
; tree_support_branch_angle = 45
; tree_support_branch_diameter = 5
; tree_support_branch_distance = 5
; tree_support_brim_width = 3
; tree_support_wall_count = 0
; upward_compatible_machine = 
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; wall_distribution_count = 1
; wall_filament = 1
; wall_generator = arachne
; wall_infill_order = inner wall/outer wall/infill
; wall_loops = 3
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_distance = 2
; wipe_on_loops = 1
; wipe_speed = 80%
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_x = 155.000
; wipe_tower_y = 220.000
; xy_contour_compensation = 0
; xy_hole_compensation = 0
; z_hop = 0.4
; z_hop_types = Normal Lift
; z_lift_type = SpiralLift
; first_layer_bed_temperature = 105
; bed_shape = 0x0,250x0,250x250,0x250
; first_layer_temperature = 260
; first_layer_height = 0.200
; CONFIG_BLOCK_END


