; Postprocessed by [ArcWelder](https://github.com/FormerLurker/ArcWelderLib)
; Copyright(C) 2020 - Brad Hochgesang
; resolution=0.05mm
; path_tolerance=5%
; max_radius=1000000.00mm
; default_xyz_precision=3
; default_e_precision=5

; generated by PrusaSlicer 2.4.0-alpha1+win64 on 2021-09-03 at 16:52:36 UTC



; thumbnail begin 64x64 3012
; iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAImUlEQVR4Ac1b20+URxTff6RWFPBWUG
; oFdhdYbgWxGLBCxQqKSLkokFrEKlYtXRovFdGWSAK2BdSk0oTaxia2SIo0bdqmNjGNDz6Y0MQmPpDU
; BxMfeJjy2+SQ2WHm+2bm+9b24YTL7s6Z85tzzvzO+c4GcnJymI40NDQ8Hh4e/hmC31Xvq6ioeHr+/P
; m7o6OjM11dXQ9115dJYWHhPNbAWlgTa6veW11d/QR7w3tbWloe6eoImGwIGzh9+vQ9KDl27NgDbJB/
; HYrxGjZSW1s758V40biBgYHfsK7MOB6ksrKyZyZrGwHAnwo2A4UwFP/r6em5j00AIBEYP0TUAUNxIA
; DGi7cFbD7En8q1a9emR0ZGfjR1PVuBDoA/Pj5+m7wNe7FdzxoACMLg1q1bN69fvz5l4362ntDf3393
; amrqa1UoJhwA0fUoAali1C9B8oVOCH7nQ9HWC4wB4BMdrzTReQAnLUt0YoI01asNABbmbwDVeyhG/b
; oJeG/r6OiYVeklgChB+gqA6Ho6m+a5gK03wGAdDsDv0zQUXQFQuZ6Ox+iSGDcATUDDZ01CMeDF9XTE
; jcSIwucYHW9zAh9rQLdTKAb8cD2dDYkkxuk9fl2pAB9rAQhVKAb4zOknj1edrixB2vJ4E28g8PkDha
; 4AvdDe3v6XV9fTERFk2zxh4w0UivBwutECMBZsbmJi4nu8+LzYXG9v75/T09NfXb16dRqbSbRO0nv5
; 8uWfoJdyWwCogMpevHjx90QWM7xQokMdMTg4+IsNiakuDrP+miC7sS+b3WnNYt81ZbGR3dnscGWIFU
; fkn6EbDSBQKAbI9aAciPhJYiBbC8NxJ0Cuh4SHv21IDIyE0Sr5Ym92nF7ZjUahGJDFilvm1JVT1cHY
; hnAyjbt3zTmRKd2GC07eyXiSwV3B2PudbjTYFlDFipfkhE3iFPgN/dCWN/9ZtPOh0wnzJEZV5Z14Pa
; gFAETnRnNkgqYkRsc94RWqGOXB5xsu/Ovdldlaxk82bWI6N5orFdYhMRAYBbfT2Ry8A15iAj55Q0NR
; Bvu2YaOrjt7NqUwnn2hXg05VXl1pOJaFdV2Tsja8xQ18kcTUFWxg0dIUNlaTzm43ZS5Z90b9yyy6YH
; xLcJmWXcZNUVmV11Oexm5qnIroome2rGKRnJB7TuEaLsfrK+dOvprMugtXsu6iFexc+Wo2sG1t7Ofx
; 4mTWmPUCa85elhgAZDEKUN4uXM3eL0lhV3au1zIep9QeXh7bqA4AfChe6GyYJQC68pNYZySJHcxbzt
; rCL7Km7BcSD4AYo2NjY3c+qAo9fW8BfUjf1jVsqjlTnZkXXscGSXQBIGkszZz/XwAAwVU1OTn5zUd1
; Rf8QABB4w5d1GUtO/UjByjjjbQBADvjPARBzAUKAB4BkqOqlmDfgp2i4DQBIvuc6G7VC4K3g8sQAIH
; v6owIAciiyQmm8CQB0G5yNnrjfXZziCkBNaI13AHBXg3nhjnfq+iYSANnTn535GexwYbISgKaSV7w3
; RXnKCeIyeuHUPVXDojZ/gxUAe4LJyo0B9L7ayPyVT4di159Ix/MXgKvJS2etkVS2PzeZ7QsnszeCa9
; iZowcfmPQ0ArJTF3k8cflobckzFY0tz8tkR4pStAGoCK1XboonVtDbtEU/T+jUE0oA3Hg8VXZ8qSme
; SkvBOkcAcOrF4UzlhqiCNK0heHGrJ5YAYMLjicZ2bFWfSk0kY9EbeAA+bNszq2q4wPOoueGlhohbU+
; OpUaCttfnRjYZNRjSWpKVko1L55tysWHIEAI3Zy1lZeKOynjApcXVqCJk3yIq5WFN06MLZuzLiosPj
; 3wyuclSOkKjK3RCX6XkOcfJQx6ws3+jIuepN2iCQNxD4aJJQngjs3bHtiUhc3Hj8O3lJMZd2A8DpVI
; aONj2yMRyCfcKrbPTyj9ZjTdG+6PH7fNI689pqZWUn8nhbANDMtDEcnoeKD7ptAKBQiGuKigAQl0dl
; R96g4vGmAOgkOpV8viM9TrcJADIytdgURbJSkRhUdsMOPN4EANX1piPIN6JuXQBU8wwUEo4AQEAxvQ
; CgIlY6wucbUwBgHCVb1TwDJKEA6BArlQxUrnWsIZwAMJlniBEhnrjoAgBGVxDOli5qSqzEU5flG10A
; TOcZFqkwERc3ANryUuZbt5cqB5JsGqT89eZmOBkPYqVKdCbzDHG1AIhLfX56nDfwAODUo91dD1SjL7
; aJjoiVaOiB0FLve3fn5jmxhPYyzyAth1HZHSpaFQdAVWjdYnIRnxp5ud5kiQ6GH1loeBwU/t9VX/2Y
; 70f4Mc+g7AfAGxoL0tj+cNISd4tld64p+kld5Kkbg5SJSKwIaApFAoDyDT+Fxk+KenmQ66kpCtRBK9
; EUNaknZIkOcV0eyogLRQCwLZQWpxMg9PX1/UF01usDXN+bom71hCzRqW6UfCHWxVEaP6ZLPDVF6Y4V
; bw9ZPYFEFy1NNeoMid4mM9bmAa4VAE5TXLLrk68nxhdCg54E+dEUddpbQiZFsQmnKS6nrjCe0jrd6U
; 4AOPF41ftNJ1xcAdCJM7/b4jpzyU6HZTKmG9BdyGkRXJe2bXERANO5ZFVIiA9wjQCw+e6Pqp5QAUDE
; ihfbuWSVaDVF+ZiWTXGZKJTVEyIAByKp8x+f6rnHA+vXXLLKG1RTaHGTos3NzX+T63kZVyUSIwOgNp
; jCaqq3P+FDy++5ZJWIo/SLTVH8QZOiOAW/JkWpniAA+PueJkVnZmYmnuekKABe0hSlSdFLly796ge1
; FL1hV27aEpanmhRNNACwDYBTfov1BAEATYrqZk5b4eOREp0XEmNy8uKNRglSOinq5UtITpugRCc7bb
; +/ayR6m2xdx0lR2y8hqVxPJ9H59V0jskHnRnNkgrrzuyaup7Nxr6Fo3BR1M4Ji1IQbeP0itW0oWjdF
; TU7FySA/v0BpEoq2ZOpfHI5pRKbJfwQAAAAASUVORK5CYII=
; thumbnail end



; thumbnail begin 400x300 15440
; iVBORw0KGgoAAAANSUhEUgAAAZAAAAEsCAYAAADtt+XCAAAtA0lEQVR4Ae2d27NV1ZXG9x/SSVA8ih
; JQGgTOBc7hQEQUGiQQUMALEERNiNeI15hoWk3aS1I2VkcSL8EyFWybVpPWoNWmO/YlVV3dPqS7Ul2p
; 8iFVnYc8+GCVDz6s3oPjjJPF2mvNtdaYc44x55eqX6GGc/bea6+1vjXHN8Y3B1NTUwWQx969e//w/P
; PP/xNB/8z5uzdv3vzh448//h/0u++4447fzc7Ofhz68wH90LlD5xCdS3ROcf7u7du3f/DMM8/8C3Hw
; 4MHfh/5swI2BpjebC/fcc89vzYW5YcOGj3y8BokG3QDoAvVxAwDpUn4A8fU6dI5+85vf/A29ziOPPP
; IeHnTkAQERBF2YTz311K/pgjl06ND7IV6TnvToNc2THi5SUAedI3R+0vmye/fuP4Z6TbMaCfWawA0I
; iBBIMHyVA5og0TCrHnrS87XqAXqJvRpA2VUmEJDIhCoHuEBei3nS4/ZdgF6MH0HnaEw/wpRdYz1ogT
; OBgEQkRjmgCboozZMmrUrwpJc39g1bysq0XHaV8J5yBQISAenmYNlgR905P2w/LvbKuIryNYSyaxwg
; IIGRUg5wfa8w2PPDXhnTOSD5vaLsGhcISEA01m/tujOe9NKGvmv6jk35Usv7tn1ElF3DAgEJgPRygA
; sY7Eobn4OrISiXXaWvnFIBAuIZTeWAJjDYlSYhBldDgbJrWCAgntBaDnABg11pEGNwNQSYawoHBMQD
; 2ssBLmCwSzcxB1dDQQ83KLv6BQLCTErlgCYw2KUPSYOrIaBrEGVXf0BAmEi1HOACBrt0IHFwNQQkGn
; RNouzKDwSEgRzKAU1gsEvHd0PnaK5P4fSgg7IrLxCQHuRWDnABBrssNA2uhgBlV14gIB2xywGYgD0d
; DHbJADfK0aDsygMEpCV2i2AORnmf44QNq+KAlbEbKLv2BwLSAtsox1OLGxjsCkuuRnnfY4ayazcgII
; 6gHNAdDHaFOcZmcJWeqjW9dwlgrqkbEJAGUA7gA8mp/o5r6oOrIUDZtT0QkBpQDuDH3rCK/sSTXj/g
; x/GDsqs7EJAKEBro//iaJz26UCHO7cl5cDUEKLu6AQEpYfJzYJT7xwx20fGmmyCE2g0MroYDZdd6IC
; AWKAeEp7xhFW6Io4EfF++4m4oE5ppOBwIyhXKABLBhVT0YXI1L2WBH2XWO7AXElAPoxMDTb1ww2FV9
; TLAylgMM9tMZ5HoA6EK04zY0vffUwWDXHBhclUm57JqzqA9yPADom5dP7oNdGFyVT85lVzO4Osipww
; DlAH3fV26DXTDKdZFjy7/9AD7IpcMARrlecqk7Y3BV93eXQ9m1/AB+ykRPvcMA5QD9pDzYhcHVNEi5
; 7DrqAfy0LqzUnvRQDkiP1Aa7sOFTWqS4YZXpVCVtKH+eQd0B0DzYhXJAuqRSdrVvNPDj0iKFh/Hyxn
; BVf2dQdwA0dhigHJAHmsuudjkAK+N00Vx2NQ/gTZ2qg6YDoOlmjHJAfmh70rMHV+m9S36vgAdNZde2
; napOk+gaOgxQDsgXDYNd9B4xuJovtOo0G35JLbt2GVwdtPnlEjsMUA4ABqllVwyuAkJy2bWr8d8qC0
; vaYJdtlKMcAAhpZVcMroIyksqufTtVO4Upxj4A9v7PKAeAKmKXXTG4CuqQUHbl6FTtnMYbq8MA5QDg
; SqyyKwZXgSsxyq6cq/Tece4hOwxQDgBtCTnYhcFV0IWQZVfuTlWW/UB8D3ahHAD6Ui67cv9+DK6Cvv
; guu/roVGXbUMpXhwH2fwZc+NiwCoOrgBMfZVefnarsOxJyGewoBwBfcJVdMbgKfMBZdvXdqeplS9u+
; HQbY/xn4ppzz0/ZBB0Y58E2fsmuoTlWve6K37TCwywEwyoFvupRdMbgKQtKl7BqyU9WrgFQdgFFPei
; gHgFi4ll0xuApi4Wqwh+5U9S4gLgcA5QAQm7q5JgyuAgnUGeyxOlWDCUjVAaCnOBjlQBL0cGOXXTG4
; CiRRFScVs1M1qIDYB+C11177h1deeeUX6JsH0qDVB5VdT548+Sr8OCARevg+evTou2+88cbrMVfGUQ
; SEygHHjx9/64UXXviltg2rQPrQU9zTTz/9bz8b/k/6NgYgT+ieeezYsXdOnDjxZsw8raACUi4H+Bjs
; AqAP5XJAucyKQcGwbJqdLPasnywOXDZxikOb5qB/pv++fd1ksW5a12fqQ1VTUswNq4IJSF13gG2wo8
; 4MYlA3uBoyTytXSARIGO7fOl48d/XK4s0DK4pf3uAO/X36uYe3j5/6PSQsmj6/C3Wdqr7jpEbhXUBc
; uwP6DnYB0BXXwVXfeVq5QasIEowT+1a2EgtXfnLdnKCksEpxeYCJsWGVVwEx5QC66Fye2soHAL32wC
; dt9382P4Oyaz++vmXCm2jUrVBIrKgkpulYdRlctR906B7s82Hci4CUVxNtf17Sjl0gTbrs/2wTe8Mq
; bdAK4Imd40FFY5SQPL1Lh5D0GVwtx0n5KruyCwhXjlWsDatA+nD5GbE2rNIGrThiC0eVkND7klja4h
; xc9b1hFWucu48xervDAHVn0AcfCc9Vg12xPp80yHsIXapqC/kk5MVIOWY+Bld9ll3ZNpTqUw5w+f3m
; ANCfeNIDbfG94RPKrqdDfoNk4ShDZnvs1YjvHCsfZdfeAhKqvdF+0qMLFXVn4ELIDZ9Qdp1DgtfRBW
; oDjiEiIXOsuMuuA6434vND25jBrhAdBkA3JtfK18p4FDEHu2JDN2FNolGGSlohRSRGjhVn2bWTgMTe
; /zlUhwHwA5U3aNjL52uEjrUuE2uwKybU3aRJLGKKiIQdVznKrq0ERNr+z747DADz9zU0VeniNBcqlT
; q4L9RYsdZVxBjsigV5CJpEogn6PL6OlaQdV/uWXZ0FROqGTxjs0sGoVk7OLhhTDqDzVNKqNHWDnTKp
; tAhDG7hXyb46VTnoWnZ1EhDbKJd6g8Zgl0xcBsj69uT3HVwNQaplV/rOpLfqdoXOS64Vsu9OVa732L
; bsOnD90Bo2fMJglyzazgGQAdt2Qljbhk+plV21teu2hT5f32OkKYizbdl1pIBo3f8Zg10y6FoTN6sR
; l+9ZajnA5b1L8hK7kvLqwz4fOVbG2nZcdS27DqpO7hT2f8ZgV6TjXjLKu1LXk6+hHOCC9rIreQRSb/
; ycdFmFxO5U5aBcdq16SDtNQFLb/xmDXWHhzjyip7+ywZ7avhyay65aBwbbQu3JrsckldWlTV3Z9U8C
; orUc4ELOg10hoJWCzxkAKoft2Kq3HNCE1g2r2m76pBXXMpbUTlWuc7RKGAeS+uZ9kuNgVwiohTPEje
; TkbZd/+PyTD7+XcoedprIr3VAl3eR909TcoaFTlYNy2XWQUjmgiZwGu0IQenjM1WDXjJaya6qzH6MY
; NaukrVOVA7vsOsjlQ9vAYO95/CLHdHdp99WG9LLrdZfm4X8YqoYK7cHV3HZPNQ/jg6mpqSJHXDoMwJ
; lI6fun1YjvPK3YSC675iwgdK+QPrgaimwFxIA8LTfoiZ+jPZcbH3lakpBadt3zhbTnP8rsXb/i1OdO
; rVO1L9kLCJFi6x0n0vv9SdioJq/pmLZFWtl125rlos8JbnbMLEu6U7UrEBAL5GmdiZZef8l7XHMhqe
; y6ZfWy4sS1f67i3OjLyQMXFw/ddsPvUu9U7QIEpATytObQsJ91FTkY7BLKriQgz+5YpOrc6Ap9zsMH
; 9vwesUhnAgGpQOtgFxfa93bIpd03ZtmVBOS7GxeoOi+6cuvqs4qNExcVIY+vFiAgNeTW7suVYyWFWH
; tchyRW2ZUE5P4vnFO8fPUSVedEW6hMd/3Kz0JARgABaSCXPC3uHCspVOVppUaMsqsRkCf/4nxV50Nb
; 6DNCQEYDAXEk1Twt3zlWUqCyXC4Ge4iyqxGQBy45p3jxqgtVnQuu0Oc6OP5ZCEgNEJAW0EVpR91rL2
; mFyrGSApXnqEyn6TtqS7ns6ut1bAF56NKx4md7l6o6F5qgzqtDU/MgIA1AQFqSSp6WdqO8Kzka7D7K
; rraAEH81NNTfvj6d2ZC7ZuefEg8ISD0QkI5oNdi1tudyk0O7r0+DvSwgxHcTERH6XDd8Ih4QkHogID
; 3QZrCnapR3BQZ7d6oE5BvDf39iaKprFhH6TCQaEBA3ICAM0NOd5DwtMo/piVvThRySXAx2U3blMNhH
; CQhBK5E391+s6hwgz8MuW0FA3ICAMEGrD4l5WrnsW92XHA32PudonYDQf//W+rHi5T06ZkRo1uOrnx
; jmEJB2QEAYoQuSsnKk5Gnlsmc1F7nkaXGUXZsE5L515xT3rptffG/z+cUb+5eJ/c4fvey8UwJhiwcE
; xB0IiAfoSS9mnhaM8n5gw6pmXAXknrXzT/23F3YuLt4S5I38zRc/XxxY+ZmhOHwGAtIDCIgnYuVpSd
; nwSTu5bVhFf7Z50GkjIMTdQ3/hvuG/H93++eKtA/GEhITjllXzigMrPgMBYQAC4plQg10E7dHw4yvT
; nAqOweObzi+mp9KfGeky19RFQA7Pnl3cuebs4u7hvz9y2bnFK9csCSImdE385YZzi/1D0fjyJ0BAeI
; CABCDEYBdBF/W9wwv3sU26WyljQ6bq4TXzT904UhcQgym7kpCQj9e0GukjIF+fOau44xPuXnv28Hxd
; UDyz7fPFa9ctZRGUn++bi5p/eOhv7Fv+Z8XeIfQnBIQfCEhAfCenGgEhHrhkrDiupAtGEj8Y3sjohm
; HIRUCI8oZVdWVXLgGxuX3IXcO/8/BwtfDk0Hyn74JWD3979ZJTvDoUGAOlAL+068Li+aG3cmTrwlOt
; w9+4ZG6G4/ohJA4kGBAQv0BAAuMzOdUWEANdhFiNNENzAA+uP/c08chNQAwuG1b5EpDbp+e47RNoLw
; 7iltXziptXzfG1IYemPneKr0x+rrhpYo4bJj4LAQkMBCQCPga7iCoBIR69fEHxemJhd5z8dLhS++rk
; vDPEI1cBMedoXdkVAgIICEhEuPO0RgmIKWnBYD8TMsqrhCN3ATGMKrtCQAABAYkMZ55WnYAYyGB/Q1
; nMhA/IKKcbU514QEDmqCq7QkAAAQERAseGVS4CAoP9TKMcAtJMuey674r1H0JAAAREEPZgV5cNq1wF
; JFeDnYxyurG5igcE5ExM2fXIQ3f/BgICICDC6LNhVVsByclgf3bH4lbCAQGpP0dvvnrbHyEgAAIilC
; 4GexcBsQ32VFcjJjAPAsIHPBBAQEAE02awi+gqIKka7K5GOQSkPRAQQEBAFOAy2EX0FRCzGnlp10Wq
; hKKKp7Zc0Es4ICD1QEAAAQFRQnmwq6qkxSEghu8Pb8AaS1p2jhUExB8QEEBAQJRRl6fFKSDGYNfU7t
; umPRcC0g8ICCAgIAoZlafFLSCmpPWjLy0SvRoZlWMFAfEHBAQQEBClVOVp+RAQ22CX2O5bl2MFAfEH
; BAQQEBDl2O2+h6/f83++BMSsRiTlaTXlWEFA/AEBAQQEJAFoNfLss8/+86vPHfmVTwGxVyMx23052n
; MhIP2AgAACAqIc2w956NaD74cQELMaiWGw+zDKISDtgYAAAgKiGOrIIuEwHVk+PZBRhMrT6pJjBQHx
; BwQEEBAQhYyaCYkhIITvPK2uOVYQEH9AQAABAVGGmUon8ShPpccSEFPS8pGn1SfHCgLiDwgIICAgij
; C5WKO2wY0pIAYugz2kUQ4Bac/G1cshIAACogESC2rVNYODo/6eBAExq5E+eVpcOVYQEH9AQAABARGO
; bZRT+aru70oREMORrQtblbS4c6wgIP64dNWKrATkksllqr6fUEBAhELGOBnkZndCl5+RJiCEa55W6P
; ZcCEg/ZobHJScBWTO5UtX3EwoIiEBoT3QSDqLN/ugSBcSUtEYZ7NSeG9soh4C059ChQ+8/uGXZRzkI
; yJfH56n6bkICAREGrTaMUb5hw4aP2vysVAExlA12KUY5BMQde3D1zqs2fJCDgOyYOF/VdxQSCIgQbK
; Ocnu66/A7pAmKvRkLkWEFAeLH9OFoZb1i9IosS1sbJJaq+p5BAQARAglHXnuuKBgEh7pqVZZRDQOqx
; B1fpHLU3M/va2guSFhCUr+qBgESkvK9H398HAYGAcFM3uEpcMb0saQHB6qMeCEgkyuUAjt8JAYGAcN
; I0uGq4ae3CJAVkz8SYmu8qFhCQwNDyv49RXgcEBALCQduV8bpV48W9XxhLSkAODEtXs1No3W0CAhIQ
; 2yivKgf0BQICAelLOeHZ9eeolHXPurFkBOSyyaVivyNJQECGrJv2/xqu5YA+QEAgIF2xB1fJMLeNcl
; eunFmShIDA93AnawEh4Xju6pXFT65bWWxfN+nlNbiN8jogIBCQLnQdXK2CROTu4UpEq4BsnrxQxHei
; hWwF5NCmidMmot88sKL4+hbem0XXckBXICAQkLb48OOonHXXUES0CQhWHu3JUkCe2Dk+MpOJViSbZv
; utRkZt+OQbCAgExBWOwdU6KGzx5tkFKgTkmvH5xbrJ5cG/gxTISkCoTHVi38rGYD9ajdAKpctr0Eqj
; rm/eJxAQCIgLXIOrTVDg4rUzi4s7Z8fECsi2iYXBjnuKZCMg928db70vBa1U2hjstlHO2Z7rCgQEAl
; JHSD/OhlYjB2YWihKQXSvHkLDLQPICQqsOMsm7bm5EP7tnfX1Jy3XDJ99AQPIVkKayq4/B1bZcvuri
; 4uDMguLWmfnRBOSWrTMfPHL3Lb8N4UnmQNICQqZ4361VbYO9ajViygF0YfosB7hAA11fmb0AAsLEjn
; EdKay0UqZz9MBlZ4qdz8HVrqydGi92rl5c3Dh9bhABuXb5Z4ut4xecWnFQNAs97NH1SqIayp9MlSQF
; hG70dUZ5V2yDnS5EUw5w3fApBKbufHjtGASkBxsn5HfkVHl6D2//tOzqe3CVg8uGqxIjJjcPVyZcAr
; JrfKz44vjCyp0ESTRMuZmaXCSIqlaSExBXo7zPauTB3Zd8xNU37wvas/r2tedBQFpyzfg5KmrjJBR1
; Zdd7brzuDyGMck6oXEiCsm3VRcWu1YuKL69eUBxcfW5x0+pzikOrzz5DQK6fml/smzyn2DO5oLhy8o
; Ji6+SiYn2LrWdNUKRZjUg/PhJJSkDqLip2Ibnzig+uuPxS0U8uZjUCAXFj84T8ITJXT+8fv7L64xfu
; PfD7ECkLmonVcp8KSQhIX6O8z2qkqu4sDVqNSCppSRMQWnVomAPo4ulxzDXlAK1AzGoEBrs76gWEyy
; jvg113lgqtRg6uWQgBKaFhDoDOrad3dV9d95lryolymzNWI82oFZC+FxU3PvO0uCAR2Tm9JPpqRIKA
; 7F85r9igIHGVWshJADjO0bZzTTliG+ya/KNYqBQQzouKEx95Wj4wMRO5Csju8TEV8x0+PD160NFQdo
; 0N2n3dUCcgIY3yrmioO8c02GMKiBaj3Hcn4ai5JvAp9gwN2n2rUSMgvi8qHxepFoM9dLtvDAHR0p4b
; 0tOjBx3pZVcJUKu+Mdiltu3HQoWAdMmxkgIM9vgCosUopxt66PNTS9k1NuSFmA23aFWCktYcogWELq
; oY7bncaDDYiVAGeygBIaO8zWBZLMp708SAxAslrXqMwU4rETLY0e4rWEAkXFScaKk7hzDYQwiIphwr
; SecoDPZmYLB/ykDiAZB0UXGjyWD3tRrxLSBac6ykoKHsGhvkac0NXw4kHQBtRnlXtAx2+TLYfQmIFq
; Ncg6enpewamxzztOz4l4GUDgPNRnlXNAx20Wpk/5pF4gXkiolFoo8jEStypyto93UjpzwtI5gm4fmU
; B0IdBuYAhO4w0HZRcaNlsGvb9FK2khangKScYyUF5Gk1Q/fM1PO0qnZcHdgHIHSHgeaLihNNBjtHuy
; +XgFx3yUrxdWdfe9PEOEeRp9VMinladTuuntGFFaLDQFqOlRRyMdj7CshN0+d+/O3bbvyd9MEuWl1L
; jNzpA/K0mkkpT8veCpm0ofz/D5oOALfBLjXHSgpaBrv6GOx9BIRKVpRjZT/pSRzs0hC50xXkablRfh
; jX9N7perIHJ0f9vUHTAeDsMEj5ouJGw2BX1zytrgJSzrEql12rnpBCk4unB4PdjbLBrqHdl1b1rjuu
; Ng4ScnQY5NKe6+MiTXHDqrYC0mSUSxnsytHTg8HuhhaD3YRH2kZ5Hc6T6F0PAIzy/qSWp9VGQFxzrG
; Imp+bu6SFPyw3JBrttlB86dOh9158btH0R1wNAF9Uzu3RdCJKhsoiGPSxc8rRcBKTrhk/0cBNysItW
; iPD05kCeVjPlsqsEg50Eo6vh3zoLy7XDYN2q8eLRyxcUr+9dquoikMiJa/+8OLxmvopgQKIpT6tJQK
; 4aP6+XWNLqI8RgV8qRO11BnpYbEsqu5QVBl9/ROUyxqcOABIRuFg9cMlb8+MoLi7evX67qQpDCD7Z9
; /k83Vi0CQtS1+9YJCFeOFV2Q9GTlo+4MT68Z5Gm5naOxyq52e26fa6NXGm9dh4EREMNjm84v3th/sa
; qLICYnD1xcPHrZeafdXDUJiKGq3bdKQHzlWNGDDmfdOcfIna4gT8uNkHFS9j2brou+1wNLnHuVwV4W
; ELMaeWnXRaoughhQyerW1WedcZPVKCBEOU+rLCC+c6w4Brtyj9zpCgx2N0LESZVzrDh+J9t+IOXBrs
; vWTn88qgb+/S0XoKQ1gseHK7VR5R2tAmIweVpGQELnWHUd7EInYX/Q7tuMzzgpX5PxrBtK2QfgyUe/
; /V5dJw4Z7Mf3LFF1EfjEGOV15rJ2ASHIYP/yzMJo28y2GexKJcdKCrQa2bpGftx+bDgNdg6jvA4vOx
; LSAWgSEFPS+tGXFmW/GrGN8tQFhJDQjtw01wSjnBfy9B5cf+4ZaQKgmnKcVJdVA5dRXoe3LW2rPJBR
; kMGeY7uvuahch+pSERApjJprQuQOLz8dVhq+OjmvMo4G1NMlTsrOsaLVts/3J0JA7HZfTRcG10UFAY
; mHXXZ96qG7fwujnJeypwcB6XaOus41tcmx4kCMgOTU7ltnlENA4vDEDV/8QNM5JJ1RnYQQkO40lV3b
; 5lhxIE5AzGokRYN91EUFAYkH9qbhp87Tg4D0o6rs2jXHigORAmKgEzEVg93VKIeAhAN70/BCnt59w+
; u27hyGgPTHLruaclWsXC3RAmLafTUb7C4XFQQkPDDKeXl2x2KncxgCwgOJxdGjR989efLkq2YwMEae
; lngBsQ12basR14sKAhIOtOfyU47cgYD4xW7PJaM8Vp4WoUJANBrsbS4qCEgYMFHOSxdPDwLSHTt8sW
; yUh8zTslElIGY1IjlPq69RDgHxcC4OjXKK0pB6zmjkqS0XdDqHISDdsI3yUfMgIfK0yqgTEMORrQvF
; lbS6XlQQEH8c2oRVBycukTsQEF7a5Fj5zNOqwpuA3Ljvmj/4FBBjsEto9+17UUFA/IAcK144OgkhIO
; 70ybEKtWEVu4CYMfqjf/29X/sWEAkGO8dFBQHhBUY5L1V700BA/MKRY1XO0/JhsLMKiD1Gv3/PlX8M
; ISCxDPa2OVYQkDBgwydeuD09CEg9bWJLXOmSp+UKm4CUuwN8eyB1qxHfF1WXHCsIiF+w4RM/XSN3IC
; Adz2EPGz4ZfAgT0VtARo3RxxAQezXiq6Tl46KCgPQD7bm8+PT0ICDV2Ea5z1mOpjyttvQSEBKMUd0B
; MQXErEY4DfZQRjkExB3kWPHj29ODgJyO/QDuY8OnUa9ZtY1BFwYcb6Dq78QWEANHnlZIoxwC4gZyrH
; gJ5elBQD7FPIDTaoDKVyFf2zbY++RotRYQ1+4AKQJCdM3T4syxgoDwgRwrXkJ6ehCQuZu3eQAn7zjm
; eym3+7b9eWcBsU0Y+vBNyx5JAmJKWm0Mdu4cKwgIw8kOo5yd0J5e7gISesMnF8oGexsPxklAunQHSB
; MQg0u7r48cKwhIP2CU8+IzcgcCUk2MDZ/aYBvsruLWKCBd62RSBcSsRqrytGJdVBCQmvMIOVbs+I7c
; gYCcTswNn7q8V7u81lRpGrh86C7dAZIFxGDnacW8qCAg1SDHipef71sWvZMwNwHhMKpDU87TqjP4Kw
; XENsq7dgdoEBCCDPbbp+WuOnIVEORY8SLF08tFQPrkWEnBJU/rNAExOVYc3QFaBIQ4OC5DICAgyLHy
; gSRPLwcB4cixkoK9B0mVwf4nAeHuDoCAQEDaghwrXiR6eikLiK+4EAmM2rDqlID46A6AgEBAXEF7Lj
; 8xI3dyFBCfOVZSsDesoj9JIAe+ugMgIBAQF9Cey4uEyJ3cBESjUd4V22An7Rj4+tAQEAhI7fkxDaOc
; GymRO7kISIwcKynQiou0Q+2WthAQxScfjHJWYuxNk7uAcHSqaudUCcvXL4eAQECqQI4VL7H2pslVQD
; g7VVMAAgIBCQKMcn6kGuWpCojEHKvYQEAgIN6BUc6L9MidFAVEeo5VLCAgEBBvYMMnfjQY5SkJiKYc
; qxhAQCAgXsCGT7xI25smBwGp23EVzAEBgYCwA6OcF4l706QsICnkWIVi4POXb1y9vLh97XkQkEwuPL
; Tn8iN1b5pUz2O7PRdGeTMD3y8wMzVRHFyzEALSkWvGzynWTK4Ud+KUQY4VL5qNco0CYocGwih3ZxDq
; hXZOLykOrx2DgLTgiolFok6WKsgoR3suLxr2pklJQGyjPNUcK18MQr7YpatWFDfPLoCANLB/5bxi3e
; RyUSdKFdjwiRfpOVYpCkhOOVY+GIR+QSppXTuzWNRqRJKA7Bg/X8zJUQdyrHjR3p6rTUBglPMwiPXC
; kgx2KQKycWKJmBNjFDDKeaH23NSMcukCktKGT7EZxHxxWo3sX7MoewGBUZ4nVLLSlGPVl9ieXsobPs
; ViEPsNENuml0YtacUUEA1GOXKs+NGYY9UVekCK7enRSiP1DZ9iIEJACDLYY7X7xhAQCReVC8ix4iUH
; o9xm28TC6Ocw2nP9IUZAiFgGe2gBkXBRNYEcK35yMcoJ6iSM7ekhx8o/ogTEENpgDyUgdFFtmFwq7n
; iXQY4VL5o2fOJAgqdncqyobIX2XH+IFBDCrEZSEZA7tk5/sHXzJvEnMnKseHnxqguzMspjd1nZ7bnY
; 8Mk/YgXEQKsR3yUt3wKyfc3FH9OTECHVwEN7Lj85tedK8PSw4VN4xAsI4TtPy5eA2Et5yS2EMMp5ST
; XHahSxPT3kWMVDhYAYfOVp+RCQURcVrUDMaiT2EBMZ5c9djVUHJ7FyrG4c/1zw15Tg6SHHKi6qBITw
; kafFKSB0UTXt21GOUYixGkGOFS+x2nNvmvhccdfs/OIrk2EF5Krx84rpYWUg9Hlrgxyr+KgTEIK73Z
; dLQNrkWJFoxLoAkGPFS6z23FuGZTJzDocUEAntucixkoFKATFwtftyCEjXi2r79u0f0BLcGOw+VyMw
; ynmJlWNFq47Dw1WHfQ6HEJBbN6748LpdO6OWXZFjJQvVAkJw5Gn1ERCOnnfbBCSD3YcJiBwrXmIZ5V
; +bmld5DvsWkJ0zSz+OWXZFjpVM1AuIoU+eVlcB4c6xotZDY7BztSEix4qfGDlWdI7ePn32yHPYl4DY
; 7bmxyq60SkeOlUySERCia55WWwHx2fNOF6V50qJVSZ8nLbTn8hLbKK87h30IyChPr1x29XlN24KF9l
; x5JCUgRBeDvY2AhOh5N096dIHShdO21kvtuTDKeYlllN82fZbTOcwpIC45VuWSEvfN3W7PhVEul+QE
; xNDGYHcRkBjhcF0MdhjlvMTKsaoyykMISFtPz55r4iq72kY5XQPc1xXgI1kBIVzztJoEJGY4nF13bn
; rS2zKzonh971JVN2jJ/HTPkig5VjevOstZODgFpGuOVTl/qmvZlX6OznHkWOkhaQExNOVp1QmIlD2c
; jZFYV3fesnpZ8cAlY8WPr7xQ1Y1aIrGM8jtmzu7UCNJHQDg8vXLZte3KATlWOslCQIi6PK0qAZG44V
; NTKyMJiPlMjw1vgG/sv1jVTVsCsdpzd4+PFZuH31/XuaauAsLt6XUpuyLHSi/ZCIihKk+rLCDSN3wa
; ladlCwhBq5HjwzKMpht4TGIZ5fYqt+tcU1sB8Zlj5TrXhA2f9JOdgBDlPC0jIFo2fCKq8rTKAmKgG+
; Pb1y9XdTMPCRnl9w2PU2jhqPPW6Lts00nYRkBotRMix8qeayqXXc2GT8ix0k2WAkLYBjsJiIRwuLaU
; B7v2XbH+w1E3mEcvXwCDvYJndywOLhyuq9x1q8ad55pcBSS0p2fPNdFqhEpcyLFKh2wFxEAG+6bJuO
; FwfaGL8ujRo+++/Mz3/rXuJmMMdqxG5oiRY+WS1mxDDzq7Zy5qXI00CYiETsITJ068SXC2/IK4ZC8g
; KUDlgGPHjr3zo8ce/E+Xp9XcDfZYRnmbtOYy9KBTt41BnYBI2PCJViHHjx9/68UXX3yHBCTWNgaAFw
; iIYso+yCgPZNRq5KVdF6m68XMQa8MnjiHUurmmKgFpu9rxQTnHqjzXBP9DNxAQpdjTuqYc0EZADEe2
; LsyipBUrx8pH6agqZaEsIH1WO1zUBS+GzNMC/oCAKKNu/+cuAmIM9pTbfWO153KnNduU55psAdGy4Z
; PvPC3gHwiIIpr2f+4qIKka7LFyrEIOoZq5JhKQmEa5ocuGT6PmmoB8ICBKcNmHoY+A2AZ7Cu2+sXKs
; YhjWNNe0fWpx1PPTzrGiVUVbg7xqrinm5wFuQECE02b/Zw4BsVcjmgTDJkaOlaYhVG64cqzKeVow2O
; UDARFM23IAl4DYqxFNJa1YRnmoyW6J+Mix6pKnBeIAARFI1/2fuQXErEY0GOwScqxywneOlWueFogL
; BEQYffZ/9iEgBql5WjFzrKSlNYciZI6VnaeF6XV5QEAE0Xf/Z58CQkjL05KcY5Ui5Y2jQr6uWZH32b
; AK8AMBEQDX/s++BcQ22GOvRjTkWKVE1eBqSMoGO9p9ZQABiYwpB3Ds/xxCQGyDPUaelsYcK83UDa7G
; AAa7LCAgkaALkbscEFJAzGokZJ6W5hwrjTQNrsainKcFgz0eEJAI+Nr/ObSAGHznacVqzyVyNcpdBl
; djYxpOkKcVDwhIYHyWA2IJCOErTytWe64ht/mONoOrEuja8g54gIAEIsT+zzEFxJS0uAx2as+NYZTn
; LCBdcqwkvXfkaYUHAhKAUOWA2AJi6GuwxzLKcxWQVJ7ikacVHgiIR0KXA6QIiL0aaSseMXKschaQPo
; OrErENduRp+QcC4okY5QBJAmKvRlxKWjGN8lwFpO/gqmTQ7hsGCAgzMcsBEgXErEbqDPbYRnluAsI1
; uCod5Gn5BwLCSOxygFQBMZTztGJt+JSzgNgr476Dq1pAnpY/ICBMSCgHSBcQwuRpxdrwKVcBoafxGD
; lWUqBVl9nwCnlafEBAeiKpHKBBQIhvDEta0oUjJQHxNbiqDeRp8QMB6YG0coAWAblrVp5ZnqqASMqx
; kgIMdj4gIB2w93+WVA6AgEBADCEGVzWDPC0eICAtkVwOgIBAQIiQGz5pB3la/YCAtEB6OQACkreAaM
; uxkgJdy8jT6gYExAEt5QAISL4CojnHSgIkGsjTag8EpAFN5QAISH4CgjRaXqikhTwtdyAgI9BYDoCA
; 5CUgqeVYSQF5Wu5AQCqIvf9zVyAg+QgIbnD+Kbf7anrvoYCAWNjlAI198xCQ9AUklxwrKZRLhGj3PR
; 0IyCfQham9HAABSVtAcsyxknTsYbCfCQRkKp1yAAQkTQGROriaG9iw6kyyFpDU+uYvXbWiOLx2DALC
; xDXj50QXEORYyaKcp5W7/zTI9QCk2je/btV4cXDNQghIT7ZNLIz+XSLHSi7I05p7AB/k1mGQQ9/8zP
; CpeffMRWJXI5IFZP/KecWGyaVRvz/kWOkg5w2rzAP4IKcOA1ppmHJADqK5cfXy4ubZBRAQR3aPj0Uv
; WSHHSh85bVhV7lQ95YHk0GGQazmAViPXziyGgDSweeLCqN8Tcqx0Q9+fubGmumFV1eDqwD4AKXYYoB
; wwB61Gbl97HgSkBBnlayZXRv1utA6ugtNJecOqUZ2qg7oDoH0JbcoBJCAoB8ytRiQY7FIEJLZRbtfQ
; YZSnQ0oGe9PKeJDiAbA/NPrmz2Tn9JKoBntsASGjfP3ksqjfgb0yRkxGepQ3rNL4AOvSqTqoOwAaOw
; zMh0bffD00MxLLYI8pIDvGz49+7JFjlQ8aN6yyB1fJ16lbQDQOEmrpMEA5oD3GYA+9GoklIBsnlkQ9
; 3jDK80TT6EDbwVWnSXS7w6BJkWKAckA/QhvsoQVEmlGOLKU8kd7t2uUB3DnKxDbY6WYt5QCgHMADrU
; b2r1mUnIBcMbEo6nHFhk/ARmK3a59O1dZZWGbHLhISerFYBwDlAD9sm17qvaQVQkBu3bjiwycf/tZ7
; Mcuu2PAJVCGp27Xv4GqnMMXYHQYoB/iFDHaf7b6+BYTac2MPdtkrY/hxoIqY3a5cD+C90nhDdxigHB
; AOnwa7LwGh9lzbKI8x2IUNn0AbYnS7cg6u9o5zD7VjF8oBcfBhsPsQkDqjPNSTnikHYMMn0JYQ3a4+
; OlXZ9gPx2WGAckBcuPO0uAXEJceqXHblPI/od2FwFfTFZ9nVV6cq64ZS3B0GKAfIglYjHCUtLgGhVc
; e6yeWtPgN32RUbPgFOfJRdfXaqsu9IyNVhgP2fZcKRp8UhIH1yrLi8NAyuAl9wlF1DdKp629K26wHA
; /s866JOn1UdAODd86lp2RcIzCEGfsmuoTlWve6K37TBAOUAXXfO0ugrIVePnsW/41LbsisFVEJo2Zd
; fQnapeBcTg0mGAcoBOurT7dhEQnxs+2U96o4QBg6sgJi7CEKNTNYiAEKM6DFAOSIM27b5tBCRkjtWo
; sisGV4EURpVdY3WqBhMQomywP/DAA/+NckA6uOZpuQpIjBwru+z6ne98578wuAqkYa+G6R4as1N1EP
; oFCVLRt99+++9feeWVX9CHx4WZFk15Wk0Csnfl2a3bc7m58847//fdd999+dixY++QiMR8LwCUoXvm
; 0aNH333nnXf+LuZwdXABMeWAH/7wh7+6//77/yfkCD8IR12eVp2ASNrw6ciRI/9udwTiQQdIgM7D8g
; ok1oZVwQTENoHow5uLUeOOXcCNUQb7KAGRsOFTuRwQI08LgFFUdaqGipOqIoiANHUHICQxbcoGe1lA
; pG34VDW4GjM5FQCiqVM1xoZV3gWkTd+89B27QHfsPC1bQHy257rQZnDVZ54WAKNo06lqG+whyq7eBK
; Rr37zEHbsAH7QauWN2rFOOFTddB1dRdgWh6LLhU8gNq7wISN++eZfBLqAX7mnyLvQdXKWfQdkV+IJj
; cDVE2ZVVQOxyAEfrY/kAcH94kB+cg6t0vqPsCrjhHFz1vWEVm4D4yrGK2WEA0qLv/s+jQNkVcOCzmc
; jXhlUsAhIix8p+0kPQImhDiBwrlF1BH0LkWNlxUvQnh0D9PyZlzO1s4wjUAAAAAElFTkSuQmCC
; thumbnail end

; ---- body elided for the test fixture ----

; prusaslicer_config = begin
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,300x0,300x300,0x300
; bed_temperature = 105
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\n;[layer_z]\n
; between_objects_gcode = 
; bottom_fill_pattern = rectilinear
; bottom_solid_layers = 5
; bottom_solid_min_thickness = 0
; bridge_acceleration = 3000
; bridge_angle = 0
; bridge_fan_speed = 30
; bridge_flow_ratio = 0.8
; bridge_speed = 60
; brim_separation = 0.1
; brim_type = outer_only
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; compatible_printers_condition_cummulative = "printer_model=~/.*Voron_v2.*/ and nozzle_diameter[0]==0.4";"printer_model=~/.*Voron.*/ and printer_notes=~/.*E3DV6.*/"
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 3000
; default_filament_profile = "Basic PLA @VORON"
; default_print_profile = 0.15mm 0.4nozzle
; deretract_speed = 30
; disable_fan_first_layers = 5
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0.1
; end_filament_gcode = ""
; end_gcode = print_end    ;end script from macro
; ensure_vertical_shell_thickness = 1
; external_perimeter_extrusion_width = 105%
; external_perimeter_speed = 80
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 70
; extruder_colour = #8000FF
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 0.94
; extrusion_width = 110%
; fan_always_on = 1
; fan_below_layer_time = 45
; filament_colour = #A768DF
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 22
; filament_density = 1.05
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 11
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "test_bed.3mf (KVP ABS @VORON - Copy)"
; filament_soluble = 0
; filament_spool_weight = 0
; filament_toolchange_delay = 0
; filament_type = ABS
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = (Unknown)
; fill_angle = 45
; fill_density = 42%
; fill_pattern = adaptivecubic
; first_layer_acceleration = 1000
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 110
; first_layer_extrusion_width = 140%
; first_layer_height = 0.2
; first_layer_speed = 25
; first_layer_speed_over_raft = 30
; first_layer_temperature = 240
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 40
; gcode_comments = 0
; gcode_flavor = reprap
; gcode_label_objects = 1
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 4000
; infill_anchor = 600%
; infill_anchor_max = 0
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 110%
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 20%
; infill_speed = 150
; inherits_cummulative = "0.2mm 0.4nozzle V2";"KVP ABS @VORON";"Voron_v2_300_afterburner 0.4 nozzle"
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]\n\nTIMELAPSE_TAKE_FRAME
; layer_height = 0.2
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 10000
; machine_max_acceleration_extruding = 1500
; machine_max_acceleration_retracting = 1500
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 9000
; machine_max_acceleration_y = 9000
; machine_max_acceleration_z = 500
; machine_max_feedrate_e = 120
; machine_max_feedrate_x = 500
; machine_max_feedrate_y = 500
; machine_max_feedrate_z = 12
; machine_max_jerk_e = 2.5
; machine_max_jerk_x = 10
; machine_max_jerk_y = 10
; machine_max_jerk_z = 0.2
; machine_min_extruding_rate = 0
; machine_min_travel_rate = 0
; max_fan_speed = 30
; max_layer_height = 0.3
; max_print_height = 300
; max_print_speed = 300
; max_volumetric_speed = 0
; min_fan_speed = 15
; min_layer_height = 0.0375
; min_print_speed = 15
; min_skirt_length = 20
; mmu_segmented_region_max_width = 0
; notes = TODO: check the size of the extruder and the y-bar clearance. Optimize & test supports.
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 1
; ooze_prevention = 0
; output_filename_format = [input_filename_base] ([filament_type]-[nozzle_diameter]).gcode
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 2000
; perimeter_extruder = 1
; perimeter_extrusion_width = 110%
; perimeter_speed = 120
; perimeters = 3
; physical_printer_settings_id = 
; post_process = "C:\\Users\\kageu\\Downloads\\SuperSlicer\\ArcWelder\\bin\\ArcWelder.exe"
; print_settings_id = test_bed.3mf (0.2mm 0.4nozzle V2 - Copy)
; printer_model = Voron_v2_300_aferburner
; printer_notes = Unoffical profile, for now.\nE3DV6
; printer_settings_id = test_bed.3mf (Voron_v2_300_afterburner 0.4 nozzle - Copy)
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 0
; resolution = 0.002
; retract_before_travel = 3
; retract_before_wipe = 0%
; retract_layer_change = 0
; retract_length = 0.75
; retract_length_toolchange = 10
; retract_lift = 0.4
; retract_lift_above = 0.2
; retract_lift_below = 500
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 50
; seam_position = nearest
; silent_mode = 0
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 3
; skirt_height = 1
; skirts = 2
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 15
; small_perimeter_speed = 40
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 110%
; solid_infill_speed = 120
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = ""
; start_gcode = print_start EXTRUDER={first_layer_temperature[0]} BED=[first_layer_bed_temperature]
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 1
; support_material_closing_radius = 2
; support_material_contact_distance = 0.35
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 110%
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 1
; support_material_interface_pattern = auto
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 70
; support_material_pattern = rectilinear
; support_material_spacing = 1
; support_material_speed = 90
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 30
; support_material_with_sheath = 0
; support_material_xy_spacing = 0.6
; temperature = 235
; template_custom_gcode = 
; thick_bridges = 1
; thin_walls = 1
; threads = 24
; thumbnails = 64x64,400x300
; toolchange_gcode = 
; top_fill_pattern = rectilinear
; top_infill_extrusion_width = 110%
; top_solid_infill_speed = 50
; top_solid_layers = 6
; top_solid_min_thickness = 0
; travel_speed = 300
; travel_speed_z = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 1
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 180
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
