; generated by SuperSlicer 2.5.59 on 2023-01-28 at 22:35:45 UTC


; ---- body elided for the test fixture ----

M98 P"0:/sys/00-Functions/Endscript"    ; execute end script
;
; =========================================================================================================
;
;_GP_LAST_LINE_M73_PLACEHOLDER
; filament used [mm] = 542.28
; filament used [cm3] = 1.30
; filament used [g] = 1.62
; filament cost = 0.06
; total filament used [g] = 1.62
; total filament cost = 0.06
; total layers count = 1
; estimated printing time (normal mode) = 12m 5s

; SuperSlicer_config = begin
; allow_empty_layers = 0
; avoid_crossing_not_first_layer = 1
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model =
; bed_custom_texture =
; bed_shape = 0x0,250x0,250x210,0x210
; bed_temperature = 60
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode =
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 4
; bottom_solid_min_thickness = 0.5
; bridge_acceleration = 0
; bridge_angle = 0
; bridge_fan_speed = -1
; bridge_fill_pattern = rectilinear
; bridge_flow_ratio = 95%
; bridge_internal_acceleration = 0
; bridge_internal_fan_speed = -1
; bridge_overlap = 90%
; bridge_overlap_min = 80%
; bridge_speed = 30
; bridge_speed_internal = 150%
; bridge_type = nozzle
; bridged_infill_margin = 200%
; brim_acceleration = 0
; brim_ears = 0
; brim_ears_detection_length = 1
; brim_ears_max_angle = 125
; brim_ears_pattern = concentric
; brim_inside_holes = 0
; brim_separation = 0
; brim_speed = 50%
; brim_width = 0
; brim_width_interior = 0
; chamber_temperature = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; compatible_printers_condition_cummulative = "printer_notes=~/.*PRINTER_VENDOR_CARIBOU3D.*/ and printer_notes=~/.*PRINTER_MODEL_(MK3S|MK3KLIPPER|DUET).*/ and nozzle_diameter[0]==0.4";"nozzle_diameter[0]!=0.8 and ! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK(2.5|3).*/ and single_extruder_multi_material)"
; complete_objects = 0
; complete_objects_one_brim = 0
; complete_objects_one_skirt = 0
; complete_objects_sort = object
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; curve_smoothing_angle_concave = 0
; curve_smoothing_angle_convex = 0
; curve_smoothing_cutoff_dist = 2
; curve_smoothing_precision = 0
; default_acceleration = 0
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.20mm QUALITY @Caribou
; default_speed = 150
; deretract_speed = 0
; disable_fan_first_layers = 1
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = ; =========================================================================================================\n;\n; generic end script for all slicers for CaribouDuet\n;\n; =========================================================================================================\n;\nG1 F1000.0                ; set feed rate\nG1 E-2                    ; retract 2mm\n;\nM568 P0 S0 R0 A0          ; turn off tool 0\n;\nM140 S0 R0                ; set bed temperature to 0C\nM140 S-274                ; set bed temperature to 0K to turn it off\n;\nM106 T0 S0                ; turn off cooling fan 0\n;\nM98 P"0:/sys/00-Functions/Endscript"    ; execute end script\n;\n; =========================================================================================================\n;\n
; enforce_full_fill_volume = 1
; enforce_retract_first_layer = 1
; ensure_vertical_shell_thickness = 1
; exact_last_layer_height = 0
; external_infill_margin = 150%
; external_perimeter_acceleration = 0
; external_perimeter_cut_corners = 0%
; external_perimeter_extrusion_spacing =
; external_perimeter_extrusion_width = 0.45
; external_perimeter_fan_speed = -1
; external_perimeter_overlap = 100%
; external_perimeter_speed = 40
; external_perimeters_first = 1
; external_perimeters_hole = 1
; external_perimeters_nothole = 1
; external_perimeters_vase = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extra_perimeters_odd_layers = 0
; extra_perimeters_overhangs = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 45
; extruder_colour = ""
; extruder_fan_offset = 0%
; extruder_offset = 0x0
; extruder_temperature_offset = 0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_spacing =
; extrusion_width = 0.45
; fan_always_on = 1
; fan_below_layer_time = 100
; fan_kickstart = 0
; fan_percentage = 0
; fan_speedup_overhangs = 1
; fan_speedup_time = 0
; feature_gcode =
; filament_colour = #FF8000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cooling_zone_pause = 0
; filament_cost = 36.29
; filament_custom_variables = ""
; filament_density = 1.24
; filament_diameter = 1.75
; filament_dip_extraction_speed = 70
; filament_dip_insertion_speed = 33
; filament_enable_toolchange_part_fan = 0
; filament_enable_toolchange_temp = 0
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_overlap = 100%
; filament_max_speed = 0
; filament_max_volumetric_speed = 0
; filament_max_wipe_tower_speed = 0
; filament_melt_zone_pause = 0
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = "Affordable filament for everyday printing in premium quality manufactured in-house by Josef Prusa"
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "Prusament PLA - Copy"
; filament_shrink = 100%
; filament_skinnydip_distance = 31
; filament_soluble = 0
; filament_spool_weight = 201
; filament_toolchange_delay = 0
; filament_toolchange_part_fan_speed = 50
; filament_toolchange_temp = 200
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_use_fast_skinnydip = 0
; filament_use_skinnydip = 0
; filament_vendor = Prusa Polymers
; filament_wipe_advanced_pigment = 0.5
; fill_angle = 45
; fill_angle_increment = 0
; fill_density = 18%
; fill_pattern = rectilinear
; fill_smooth_distribution = 10%
; fill_smooth_width = 50%
; fill_top_flow_ratio = 100%
; first_layer_acceleration = 0
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 60
; first_layer_extrusion_spacing =
; first_layer_extrusion_width = 0.42
; first_layer_flow_ratio = 100%
; first_layer_height = 0.2
; first_layer_infill_speed = 20
; first_layer_min_speed = 25
; first_layer_size_compensation = -0.2
; first_layer_size_compensation_layers = 1
; first_layer_speed = 40
; first_layer_speed_over_raft = 30
; first_layer_temperature = 215
; full_fan_speed_layer = 4
; fuzzy_skin = none
; fuzzy_skin_point_dist = 200%
; fuzzy_skin_thickness = 150%
; gap_fill_acceleration = 0
; gap_fill_enabled = 1
; gap_fill_extension = 0
; gap_fill_flow_match_perimeter = 0%
; gap_fill_last = 0
; gap_fill_max_width = 0
; gap_fill_min_area = 100%
; gap_fill_min_length = 0
; gap_fill_min_width = 0
; gap_fill_overlap = 100%
; gap_fill_speed = 40
; gcode_comments = 0
; gcode_filename_illegal_char = [<>:"/\\\\|?*]
; gcode_flavor = reprapfirmware
; gcode_label_objects = 1
; gcode_precision_e = 5
; gcode_precision_xyz = 3
; gcode_resolution = 0
; gcode_substitutions = M107;"M106 S0";;;(?-s)^G10.*;";";r;
; high_current_on_filament_swap = 0
; hole_size_compensation = 0
; hole_size_threshold = 100
; hole_to_polyhole = 0
; hole_to_polyhole_threshold = 0.01
; hole_to_polyhole_twisted = 1
; host_type = octoprint
; infill_acceleration = 0
; infill_anchor = 2.5
; infill_anchor_max = 12
; infill_connection = connected
; infill_connection_bottom = connected
; infill_connection_bridge = connected
; infill_connection_solid = connected
; infill_connection_top = connected
; infill_dense = 0
; infill_dense_algo = autoenlarged
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_spacing =
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 80
; inherits_cummulative = "0.20mm QUALITY SLOW @Caribou";;"CaribouDuet 220"
; init_z_rotate = 0
; interface_shells = 0
; ironing = 0
; ironing_acceleration = 0
; ironing_angle = -1
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 50%
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.2
; lift_min = 0
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 1250,1250
; machine_max_acceleration_retracting = 1250,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 1000,960
; machine_max_acceleration_y = 1000,960
; machine_max_acceleration_z = 200,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 200,100
; machine_max_feedrate_y = 200,100
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 4.5,4.5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 0.4,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_gcode_per_second = 1500
; max_layer_height = 0.3
; max_print_height = 217
; max_print_speed = 200
; max_speed_reduction = 90%
; max_volumetric_speed = 0
; milling_after_z = 200%
; milling_extra_size = 150%
; milling_post_process = 0
; milling_speed = 30
; milling_toolchange_end_gcode =
; milling_toolchange_start_gcode =
; min_bead_width = 85%
; min_fan_speed = 100
; min_feature_size = 0.1
; min_layer_height = 0.05
; min_length = 0.035
; min_print_speed = 15
; min_skirt_length = 4
; min_width_top_surface = 100%
; mmu_segmented_region_max_width = 0
; model_precision = 0.0001
; no_perimeter_unsupported_algo = none
; notes =
; nozzle_diameter = 0.4
; only_one_perimeter_first_layer = 0
; only_one_perimeter_top = 1
; only_one_perimeter_top_other_algo = 0
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{filament_type[0]}_{printer_model}_{print_time}.gcode
; over_bridge_flow_ratio = 100%
; overhangs_acceleration = 0
; overhangs_reverse = 0
; overhangs_reverse_threshold = 250%
; overhangs_speed = 100%
; overhangs_width = 0
; overhangs_width_speed = 0
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 0
; perimeter_bonding = 0%
; perimeter_extruder = 1
; perimeter_extrusion_spacing =
; perimeter_extrusion_width = 0.45
; perimeter_generator = classic
; perimeter_loop = 0
; perimeter_loop_seam = rear
; perimeter_overlap = 100%
; perimeter_round_corners = 0
; perimeter_speed = 80
; perimeters = 3
; physical_printer_settings_id =
; post_process =
; print_custom_variables =
; print_extrusion_multiplier = 100%
; print_retract_length = -1
; print_retract_lift = -1
; print_settings_id = 0.20mm QUALITY SLOW @Caribou - Copy
; print_temperature = 0
; printer_custom_variables =
; printer_model = Caribou_Duet_220
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_CARIBOU3D\nPRINTER_MODEL_DUET\n
; printer_settings_id = CaribouDuet 220 - Copy
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor =
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_interface_layer_height = 0
; raft_layer_height = 0
; raft_layers = 0
; remaining_times = 1
; remaining_times_type = m73
; resolution = 0.0125
; resolution_internal = 0.1
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 1
; retract_length = 0.4
; retract_length_toolchange = 4
; retract_lift = 0.4
; retract_lift_above = 0
; retract_lift_below = 216
; retract_lift_first_layer = 0
; retract_lift_top = "All surfaces"
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 25
; seam_angle_cost = 30%
; seam_gap = 15%
; seam_position = rear
; seam_travel_cost = 70%
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_brim = 0
; skirt_distance = 2
; skirt_distance_from_brim = 1
; skirt_extrusion_width = 130%
; skirt_height = 3
; skirts = 1
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 0
; small_perimeter_max_length = 20
; small_perimeter_min_length = 6
; small_perimeter_speed = 25
; solid_fill_pattern = rectilineargapfill
; solid_infill_acceleration = 0
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_spacing =
; solid_infill_extrusion_width = 0.45
; solid_infill_overlap = 100%
; solid_infill_speed = 80
; solid_over_perimeters = 2
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = ""
; start_gcode = ; =========================================================================================================\n;\n; start script for PrusaSlicer for CaribouDuet\n;\n; =========================================================================================================\n;\nT0                               ; select tool 0\n;\nM568 P0 S160 R160 A2             ; pre-heat extruder to 160°C\n;\nG90                              ; absolute positioning\nG0 X125 Y-7 Z80 F4000            ; move extruder above bed, keep extruder in front for cleaning and checking\n;\nM140 S[first_layer_bed_temperature]                         ; this will take the layer 1 temperature for bed 0\nM190 S[first_layer_bed_temperature]                         ; wait for bed temp\n;\nG29                              ; mesh bed leveling using defined mesh grid\nG0 X0 Y-3 Z0.6 F4000             ; go outside print area\n;\nM568 P0 S[first_layer_temperature] A2                  ; set extruder temperature\nM109 S[first_layer_temperature]                        ; wait for extruder temp\n;\n; =========================================================================================================\n;\nM98 P"0:/sys/primeLine.g"        ; execute primeline macro\n;\nG92 E0.0                         ; set extruder position\nM572 D0 S0.07                    ; set pressure advance\n;\n; =========================================================================================================\n;\n
; start_gcode_manual = 0
; support_material = 0
; support_material_acceleration = 0
; support_material_angle = 0
; support_material_angle_height = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0.1
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.1
; support_material_contact_distance_type = filament
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.35
; support_material_interface_acceleration = 0
; support_material_interface_angle = 90
; support_material_interface_angle_increment = 0
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_fan_speed = -1
; support_material_interface_layer_height = 0
; support_material_interface_layers = 2
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 80%
; support_material_layer_height = 0
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 50
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 55
; support_material_with_sheath = 0
; support_material_xy_spacing = 50%
; temperature = 215
; template_custom_gcode =
; thin_perimeters = 100%
; thin_perimeters_all = 20%
; thin_walls = 1
; thin_walls_acceleration = 0
; thin_walls_merge = 1
; thin_walls_min_width = 50%
; thin_walls_overlap = 50%
; thin_walls_speed = 100%
; threads = 20
; thumbnails = 0x0,160x160
; thumbnails_color = #107C18
; thumbnails_custom_color = 1
; thumbnails_end_file = 0
; thumbnails_format = QOI
; thumbnails_with_bed = 1
; time_cost = 0
; time_estimation_compensation = 100%
; time_start_gcode = 20
; time_toolchange = 30
; tool_name = ""
; toolchange_gcode =
; top_fan_speed = -1
; top_fill_pattern = monotonic
; top_infill_extrusion_spacing =
; top_infill_extrusion_width = 0.4
; top_solid_infill_acceleration = 0
; top_solid_infill_speed = 40
; top_solid_layers = 5
; top_solid_min_thickness = 0.7
; travel_acceleration = 0
; travel_deceleration_use_target = 1
; travel_speed = 180
; travel_speed_z = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_add_middle_threshold = 75%
; wall_distribution_count = 1
; wall_split_middle_threshold = 50%
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 0.4
; wipe = 1
; wipe_advanced = 0
; wipe_advanced_algo = linear
; wipe_advanced_multiplier = 60
; wipe_advanced_nozzle_melted_volume = 120
; wipe_extra_perimeter = 0
; wipe_inside_depth = 50%
; wipe_inside_end = 1
; wipe_inside_start = 0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_only_crossing = 1
; wipe_speed = 0
; wipe_tower = 1
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 125
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_inner_size_compensation = 0
; xy_size_compensation = 0
; z_offset = 0
; z_step = 0.0025
; SuperSlicer_config = end
;
; thumbnail begin 300x300 5420
; iVBORw0KGgoAAAANSUhEUgAAASwAAAEsCAYAAAB5fY51AAAPp0lEQVR4Ae3dy5IcVxWF4XoVC2ywsE
; 1IJdmWAMMUEbK4B5gJI3MRAQQ3cwlDOXgIMBMbA8/CY5UrW52hUqkumXn2Pmevs//BN3UvZZ38u5Rq
; d63W6/UKABRIjQWQm9RYALlJjQWQm9RYALlJjQWQm9RYALlJjQWQm9RYALlJjQWQm9RYALlJjQWQm9
; RYALlJjQWQm9RYALlJjQWQm9RYALlJjQWQm9RYALlJjQWQm9RYALlJjQWQm9RYALlJjQWQm9RYALlJ
; jQWQm9RYALlJjQWQm9RYALlJjQWQm9RYALlJjQWQm9RYALlJjQWQm9RYALlJjQWQm9RYALlJjQWQm9
; RYALlJjQWQm9RYALlJjQWQm9RYALlJjQWQm9RYALlJjQWQm9RYALlJjQWQm9RYALlJjQWQm9RYALlJ
; jQWQm9RYALlJjQWQm9RYALlJjQWQm9RYALlJjQWQm9RYALlJjQWQm9RYALlJjQWQm9RYALlJjQWQm9
; RYALlJjQWQm9RYALlJjQWQm9RYALlJjQWQm9RYALlJjQWQm9RYALlJjQWQm9TYSN5/cH9zidKfB1Ag
; NbaVMUD///HXtksQMMCG1NjalgaKeAE+pMbWUPJOakm8lK4N0JrUWG+1QkW4gGWkxnppFSqiBcwjNd
; ZDhFgRLWAaqbHWIsWKcAGXSY21FDVWBAs4TWqslZr/Eki0ADtSY61EjxXRAo6TGmtBJVYEC3ie1FgL
; SsEiWsCzpMaWUnh2RbCA06TGllIK1T6lawx4khpbSilSBGse3onmIDW2lFKkCNb815Vo9U9qbCmlSB
; GsZa8p0eqb1NhSKoEiWOWvJeHqk9TYUv95dFciUATrvKnXjWj1R2psKcVg/fPBLYJ1bcmPpfAbXvsi
; NbbUB1+9GT5Qhx7fuUGw1uV/nSdafZAaW2oI1v++qfMu68PduyuCZffskWjpkxpbagjW34Wi9fjOZ1
; IHy+u6Ei5dUmNLKQXrF1exyhss7+tLtDRJjS01Bit6tIZYZQ1W7f/fk3BpkRpbaj9YUaP1+DpWGYPV
; 6poTLR1SY0sdBmvw30A/6vD4OlLZghXht2jw4w8apMaWOhasD966ud289fK29c9oDWHKGKzWoToWLq
; Xrl43U2FLngvW3nU920frk7TtVb5CfrW9sf76+kTJYUSJFtHRIjS11KVh//crL2/e//Pntv3fR+tg5
; XP/4+q2rWGUMVrRAES4dUmNLTQ3WX3b+/KXPbT9+eOeKZaTevfXC9ie3X9j+dCdjsCKGiWjpkBpbam
; 6w/nT/iT9e+2gXr48erq9cOuj/+sbt7YcPbl/9tPoQpSFS7w6SBkvx11PvR4twxSA1tlRpsAbv3X9p
; +969l7Z/2Pn9zu/efHH722u/eePF7a9f/+z2Vzu/vDtG50b6YCnFiXdbsUmNLUWw6lMKEtGKT2psKY
; JVj1KECJcOqbGlCFYdSuEhWlqkxpYiWL6UH6yXRItw1SM1thTB8qMUGd5t6ZIaW4pg+Xjn3msb1d+X
; b2V4DaO/Tj2QGluKYPkYgjVcwwj/T2aLUI2iv049kBpbimD52A9Wpmjtx4pg1SE1thTB8nEYrDFavY
; Zr+CSjw1gRrDqkxpYiWD6OBavXd1vHQkWw6pEaW4pg+TgXrJ6idS5WBKsOqbGlCJaPS8FSD9elUBGs
; eqTGliJYPqYGSzFaU2NFsOqQGluKYPmYEyyVcJ16sE6w2pIaW4pg+VgSrMjRmhsqglWP1NhSBMvH0m
; BF+/GHJe+qCFZdUmNLESwfJcGK8m6rJFQEqx6psaV+dO+LG4JlzyJYLaNlESuCVYfU2FKKwXp05wub
; 6NfVKli1w2UVKoJVj9TYUorBUriu1sGqES3rWBGsOqTGWjiMFsEq5xEsrwfypQ/WCVZbUmMtKAVL5Z
; p6Bcv63ZZXqAhWPVJjrexHi2CV8w6WRbS8Y0Ww6pAaa2mMVtRgKV3LGsFaGq4aoYoerPFa9PBrnKXG
; WhuiFTFYStdwUDNYc6JVM1ZRg3V4TdQ/NENqrId3dtGKFCyla/f0GtYN1hitU+HyfLCuEqxLn2CkGi
; 2psV6GGy5CsJSu2eH1qx2sU++2WoQqWrCm/nVZMVpSYz398M3XNj/YaREspet0TMtg7b/bahmrKMFa
; 8g8SSuGSGFnTEK1awXp7Xf5T7BEOXetgDYbXInOwSn/kQyVa4Qe28v03Xt0MPIL1cH1zY7ExyqEjWG
; 2DVRorpXCFHRbJGK+lwRreSVlFanDpwNU+dASrTbAuPVjvMVohR0X3vddf3Qy+e+WVzXcGd1/ZfHvn
; W9e8vnbEQ0ew6gfLI1Stv/FNEWoMTlvy3bTWoSNYdYPlHavI77bCDMFp0Q8dwaoTrJqhihqtECNwms
; KhI1j+wWoVq2jhWrUegOOUDh3B8gtWhFBFitaq5RfHcWqHjmD5BCtSqA7PT6twrVp8UbQ/oJaHbghW
; 62i1Dtajtd2vsvb6cYXo3/imWNX+gjiuh0PXMlotg9XDOVCJ1qrmF8PzInw37SFarYJleRYiBCjCGT
; pnVeOLQOOAKoerdrB6PgcRzs8pK+8vAK1DqhqtmsHKcA5Kzo9nuFxvSmgeUOtDVyNcNYKV8cF6yRny
; uH/cb1A8pXTgrA+dd7S8g5X5HJScH+twud+k0P5uah0tr3B5BcvyXdVA6bWPeIbcb9bslA5WzXApBI
; tzEO/8VLlps1I6UDUP3cA6WtbB4hzYsrqm1W7eTJQOUi/hsgqW5Tno/cH6FPufYGRxTavdxFkoHaae
; omURLM6BLY/rW+1G7p3SQbKMVpT/H7EkWPy4gj2vbwjVbuieKR0kDxHebS0NFufAlve1rnZT92q4wa
; Z+dHqvrP/pf0m0lgTLcrPS6+WlxvWuclP3bLy5zn10eu8H1DpYh9fWOliWG5VeLy/7D9YJVnCHN1WW
; aHk9A7p0fUuDZblN6fWqcQ4IloBjN1TP77aOfTf1DNZ4jS+F61KweLBur8Vfwd1v6N6du5F6i1aNGC
; y91ueCZblB6fXyMjdUBCuQS9/5e4jWpWcUtYI1Xu9j1/xUsCy/ttJr5mVprAhWEFOfsaiGa8pBrBms
; U9f9MFiWX0vp9Wp5DgiWgDn/kqUWrakHsUWwDq/9frAsv4bS69X6HBAsAXN/Zkjhgfzcg9gqWPuvwR
; Asy/8mD9an/7gCwRKy9Cezo0ZryUFsHSxrEV8XhXNAsASU/P9vkaJV8t20p2BFeT1a8ogVwQrC4jcN
; tA5X6UHsIVgRQtGaV6gIViBWv8+pVbQsDqJ6sKIEoyXvWBGsICx/c2bNB/KWB1E1WJGC0Yr1g3WCFZ
; zH7yf3jpb1QVQMVrRwtFArVAQrEK9PgfGIltd3U6Vg8eMKbWJFsILw/rw9q3B5HkSVYEWNR00tQkWw
; Aqnxqcal0fI+iArBihqQmlrGimAFUSNYS8NV6yBGDlb0iNRQ88E6wQquZrDmRKvmQYwarOghqSFCqA
; hWILWDNUbrVLhaHMRoweLBepx3VQQrmBbBOvVuq9VBjBQslaB4ihAnghVUy2CN0Wr93TRKsJSiki1W
; BCuI1sEatD6IrYOlFJSMoSJYgRCstsFSikrmWBEsgpU6WDxYj/lgnWARLIJ1QCkqXiIEiGARLIJ1Bu
; +qdGNFsAhWqmApBYVQ2YeKYBEsmWApRYVY+cWKYBGs0MFSCooXtQfr3meiyU1OsAgWsbosQniW8Lzf
; mtzkvQWrdbR6OqA8WNd9V+UdK4JlHK6MwbK8hkpR8RIhOhFDRbActIpWD4dUKSqKsRo+GVvhHFzS5M
; buXe1weR1EQqUfqvGMeASrxb21avFFM6gZLc8DT6z0Y+URrFb31arVF86g1gN5z0PvcUB5sO77YH2I
; 0+EZsQpW69/MsWr5xbPwjpZnqKxjpRQVL56v1akzYhGsCPdS8wFZeEbL6/BbfjflXVW7WFkEK8p9FG
; JEJh7h8jj8ln9mpaD0FqrSYEW7f0KNycI6WpFjNTj3oRkZtI7V0mBFvHfCDcrC8oF81FCNxp3ZouX5
; YH346/qc8zMnWJE/ZzLkqEwsohU5VoP9rVmi5RWqw9dq6je+qcGKdG8cE3pcFqXRKv1O7f3nO7a553
; DVitWcMzQlWBHuhUvCD8xkabisD7+1U7t7i1aLUE09P+eC1frczyEzNIsl0Yocq8G57b08kG8dq0tn
; 6FSwWp3zpaTGZjInXFFDNZryZ1CNlmeoSv66fnh+DoMV+cH6OVJjs5karcixGkwNr1q0Ir2rOnV+xj
; O0H6xW58CC1NiMpvwrUNRQjeb+FTd6uLx/XMHjDA3BUn1XtU9qbGbnohU5VoO5wYocrejvqnonNTa7
; U9Gq9Z16qSXBivhAnli1JzUWTxyGK/rhXxqsKO+2CFUcUmPx1H60ot8ApcFqGS1iFYvUWDxrfCAf/f
; BbBKt2uNQerGchNRaaLINVI1q8q4pLaiw0WQfLM1zEKjapsdDkFSzLaHmGiljZkRoLTZ7BGqNVEi7v
; WBEsO1Jjock7WEvfbdX8SHil1ysyqbHQVCtYc6JVK1QEy5bUWGiqGaxL4ar5ropg2ZMaC00tgnUsWi
; 1CRbBsSY2FplbBGqM1aBkrgmVHaiw0tQzWwOpj2glWe1JjoYlgESwrUmOhiWARLCtSY6GJYBEsK1Jj
; oYlgESwrUmOhiWARLCtSY6GJYBEsK1JjoYlgESwrUmOhiWARLCtSY6FpzqdYEyycIzUWulpGq2WwlF
; 4jBVJjoW3Kp1j3FCyl10aF1Fj0oXa0ageLT8XxIzUW/agZrZrBUnoNFEmNRX9qhKtGsHhXVYfUWPTJ
; O1rewVK61uqkxqJfng/kPYOldI17IDUW/fOIlkewlK5pT6TGIgfraFkHS+la9kZqLHKxCpdVsHiw3p
; 7UWORjES2LYClds55JjUVeJeEqDZbSdeqd1FjktjRaS4OldG2ykBoLLPnxhyXBUrommUiNBUZzojUn
; WDxYj01qLLBvarSmBkvpz56V1FjgmEvhuhQs3lXpkBoLnHIuWueCpfRnBMFCR049kD8VLKU/G56QGg
; tMcRitw2Ap/VnwLKmxwFT70doPltKfAc+TGgvMNYRrCBYP1vsgNRZAblJjAeQmNRZAblJjAeQmNRZA
; blJjAeQmNRZAblJjAeQmNRZAblJjAeQmNRZAblJjAeQmNRZAblJjAeQmNRZAblJjAeQmNRZAblJjAe
; QmNRZAblJjAeQmNRZAblJjAeQmNRZAblJjAeQmNRZAblJjAeQmNRZAblJjAeQmNRZAblJjAeQmNRZA
; blJjAeQmNRZAblJjAeQmNRZAblJjAeQmNRZAblJjAeQmNRZAblJjAeQmNRZAblJjAeQmNRZAblJjAe
; QmNRZAbp8Cvk44TOQMavUAAAAASUVORK5CYII=
; thumbnail end
;
