package gcode

import (
	"bytes"
	"encoding/json"
	"os"
	"strconv"
	"strings"
	"testing"
)

func f(v float64) *float64 { return &v }
func i(v int) *int         { return &v }
func b(v bool) *bool       { return &v }

// TestParseFixtures reads the real output of five slicers.
//
// The fixtures are genuine captures with their bodies elided, not hand-written
// examples, because the failures worth catching here are all cases where a
// slicer does something nobody would think to invent: OrcaSlicer writing a fake
// SuperSlicer generator line, PrusaSlicer writing five comma-separated
// temperatures, Cura writing filament length in metres. A test against invented
// headers would pass while the parser was useless on every real file.
//
// The whole Meta is compared rather than a field or two, so an added key that
// accidentally populates an unrelated field fails here instead of shipping.
func TestParseFixtures(t *testing.T) {
	for _, tc := range []struct {
		file string
		want Meta
	}{
		{
			// A five-extruder MMU print. Proves the totals are summed across
			// extruders while the settings take extruder one, and that
			// `filament_cost = 27.82` (the price of a kilogram of PETG) never
			// reaches the cost field, which is `total filament cost = 0.01`.
			file: "prusaslicer.gcode",
			want: Meta{
				Slicer: "PrusaSlicer", SlicerVersion: "2.9.2",
				LayerHeightMm: f(0.2), InfillPercent: f(15), InfillPattern: "grid",
				WallLoops: i(2), TopLayers: i(5), BottomLayers: i(4),
				NozzleTempC: f(230), BedTempC: f(80), PrintTimeSeconds: i(57),
				FilamentGrams: f(0.2), FilamentMm: f(65.73), FilamentType: "PETG",
				FilamentCost: f(0.01), MaxVolumetricSpeed: f(9),
				PrinterModel: "XL5IS", Supports: b(false),
				// bed_shape is a rectangle and the colour list has five
				// identical entries, of which line() already keeps the first.
				BuildVolume: &BuildVolume{
					MaxXMm: 360, MaxYMm: 360, HeightMm: 360,
				},
				FilamentColor: "#ff8000",
			},
		},
		{
			// SuperSlicer sets both volumetric speed keys to 0, which in every
			// Slic3r-lineage slicer means "no limit". Reporting "0 mm³/s" would
			// tell the reader the opposite of what the file says, so the field
			// must be absent.
			file: "superslicer.gcode",
			want: Meta{
				Slicer: "SuperSlicer", SlicerVersion: "2.5.59",
				LayerHeightMm: f(0.2), InfillPercent: f(18), InfillPattern: "rectilinear",
				WallLoops: i(3), TopLayers: i(5), BottomLayers: i(4),
				NozzleTempC: f(215), BedTempC: f(60), PrintTimeSeconds: i(725),
				FilamentGrams: f(1.62), FilamentMm: f(542.28), FilamentType: "PLA",
				FilamentCost: f(0.06),
				PrinterModel: "Caribou_Duet_220", Supports: b(false),
				BuildVolume: &BuildVolume{
					MaxXMm: 250, MaxYMm: 210, HeightMm: 217,
				},
				FilamentColor: "#ff8000",
			},
		},
		{
			// Six lines below its real generator line this file says
			// "generated by SuperSlicer 1.5.0", a deliberate lie Orca writes so
			// that preprocess_cancellation accepts the file. First match in
			// file order is the only thing keeping this from being reported as
			// SuperSlicer.
			//
			// It also has `gcode_flavor = klipper` and a Klipper printer, which
			// is what a "Klipper file" actually is: Klipper is firmware, and
			// the slicer that wrote this was Orca.
			file: "orcaslicer_1.5.gcode",
			want: Meta{
				Slicer: "OrcaSlicer", SlicerVersion: "1.5.0",
				LayerHeightMm: f(0.2), InfillPercent: f(15), InfillPattern: "grid",
				WallLoops: i(3), TopLayers: i(4), BottomLayers: i(3),
				NozzleTempC: f(260), BedTempC: f(105), PrintTimeSeconds: i(220),
				FilamentGrams: f(0.59), FilamentMm: f(235.72), FilamentType: "ABS",
				FilamentCost: f(0.01), MaxVolumetricSpeed: f(12),
				PrinterModel: "Generic Klipper Printer", Supports: b(false),
				// Orca writes printable_area *and* bed_shape with the same
				// value; its own key is the one asked for first.
				BuildVolume: &BuildVolume{
					MaxXMm: 250, MaxYMm: 250, HeightMm: 250,
				},
				FilamentColor: "#f2754e",
			},
		},
		{
			// A hyphenated version, which must survive whole: splitting
			// "2.3.2-dev" the way "BambuStudio-02.07.01.62" has to be split
			// would report version "2.3.2" and lose the dev marker.
			file: "orcaslicer_2.3.gcode",
			want: Meta{
				Slicer: "OrcaSlicer", SlicerVersion: "2.3.2-dev",
				LayerHeightMm: f(0.2), InfillPercent: f(20), InfillPattern: "crosshatch",
				WallLoops: i(2), TopLayers: i(4), BottomLayers: i(3),
				NozzleTempC: f(210), BedTempC: f(55), PrintTimeSeconds: i(365),
				FilamentGrams: f(1.12), FilamentMm: f(375.61), FilamentType: "PLA",
				FilamentCost: f(0.02), MaxVolumetricSpeed: f(12),
				PrinterModel: "IdeaFormer IR3 V2", Supports: b(false),
				// A belt printer: 250 x 2000 mm of bed and 250 mm of height,
				// which the toolpaths in machine coordinates sit nowhere near.
				// This file also writes `extruder_printable_height = 0` before
				// the real key and `default_filament_colour = ""` before the
				// real colour; exact key matching is what keeps both out.
				BuildVolume: &BuildVolume{
					MaxXMm: 250, MaxYMm: 2000, HeightMm: 250,
				},
				FilamentColor: "#26a69a",
			},
		},
		{
			// Bambu names its version with a hyphen, states its bed by plate
			// name rather than temperature - "Textured PEI Plate" has to be
			// resolved through curr_bed_type to 60 - and writes two statements
			// on one colon line. It has `filament_cost = 24.99` and no total,
			// so its cost row must be absent rather than claiming this 36 g
			// print cost twenty-five dollars.
			file: "bambustudio.gcode",
			want: Meta{
				Slicer: "Bambu Studio", SlicerVersion: "02.07.01.62",
				LayerHeightMm: f(0.2), InfillPercent: f(15), InfillPattern: "gyroid",
				WallLoops: i(3), TopLayers: i(5), BottomLayers: i(3),
				NozzleTempC: f(220), BedTempC: f(60), PrintTimeSeconds: i(2838),
				FilamentGrams: f(36.71), FilamentMm: f(12250.44), FilamentType: "PLA",
				MaxVolumetricSpeed: f(21),
				PrinterModel:       "Bambu Lab X1 Carbon", Supports: b(true),
			},
		},
		{
			// Cura shares almost no spelling with the others: `;LAYER_HEIGHT`,
			// a bare `;TIME:35` in seconds, and a filament length in *metres*.
			// Three fields is all this slicer gives up without parsing its
			// SETTING_3 block, and three fields is still a panel.
			file: "cura.gcode",
			want: Meta{
				Slicer: "Cura", SlicerVersion: "master",
				LayerHeightMm: f(0.1), PrintTimeSeconds: i(35),
				FilamentMm: f(8.29066),
			},
		},
	} {
		t.Run(tc.file, func(t *testing.T) {
			got, ok := parseFile(t, "testdata/"+tc.file)
			if !ok {
				t.Fatal("Parse returned false for a real slicer file")
			}
			if a, b := jsonOf(t, got), jsonOf(t, tc.want); a != b {
				t.Errorf("parsed:\n%s\nwant:\n%s", a, b)
			}
		})
	}
}

// TestParseIgnoresFreeText is the reason `=` lines are never split on `;`.
//
// PrusaSlicer writes its config block in alphabetical order, so filament_notes,
// notes and printer_notes - three fields the user types into freely - are all
// scanned before layer_height, perimeters and temperature. If a `=` value were
// split into further statements, anyone could put "temperature = 999" in their
// filament notes and the panel would believe it. First-occurrence-wins makes
// that the *winning* value, not a losing one.
func TestParseIgnoresFreeText(t *testing.T) {
	src := strings.Join([]string{
		"; generated by PrusaSlicer 2.9.2 on 2025-01-01 at 00:00:00",
		"G1 X0 Y0",
		"; filament_notes = temperature = 999; layer_height = 9.9; perimeters = 99",
		"; filament_type = PETG",
		"; layer_height = 0.2",
		"; perimeters = 2",
		"; printer_notes = generated by Cura 5.7.1",
		"; temperature = 230",
		"",
	}, "\n")

	got, ok := Parse(strings.NewReader(src), int64(len(src)))
	if !ok {
		t.Fatal("Parse returned false")
	}
	if got.Slicer != "PrusaSlicer" {
		t.Errorf("slicer = %q, want PrusaSlicer; a generator name inside free text was believed", got.Slicer)
	}
	if got.LayerHeightMm == nil || *got.LayerHeightMm != 0.2 {
		t.Errorf("layer height = %v, want 0.2", deref(got.LayerHeightMm))
	}
	if got.WallLoops == nil || *got.WallLoops != 2 {
		t.Errorf("wall loops = %v, want 2", derefInt(got.WallLoops))
	}
	if got.NozzleTempC == nil || *got.NozzleTempC != 230 {
		t.Errorf("nozzle temp = %v, want 230", deref(got.NozzleTempC))
	}
}

// TestParseUnknownSlicer covers the acceptance criterion that a file we cannot
// attribute produces no panel.
//
// The input is a real PrusaSlicer fixture with only its generator line removed,
// so the config block still parses perfectly and sixteen fields are still
// found. Returning true here would put a settings panel on the page with no
// slicer name in its footer, which is the app claiming to understand a file it
// does not.
//
// The second case is why generator detection is anchored to the start of a
// comment rather than searched for anywhere in the line. A user types their own
// text into filament_notes, and it lands in the config block of whatever file
// they slice. If that text can name a slicer, an unrecognised file becomes a
// recognised one and the panel starts reporting a slicer that never touched it.
func TestParseUnknownSlicer(t *testing.T) {
	raw, err := os.ReadFile("testdata/prusaslicer.gcode")
	if err != nil {
		t.Fatal(err)
	}
	var kept []string
	for _, line := range strings.Split(string(raw), "\n") {
		if !strings.Contains(strings.ToLower(line), "generated by") {
			kept = append(kept, line)
		}
	}
	stripped := strings.Join(kept, "\n")

	for _, tc := range []struct {
		name string
		src  string
	}{
		{"no generator line", stripped},
		{
			"generator name only in free text",
			"; filament_notes = generated by PrusaSlicer 9.9\n" + stripped,
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			got, ok := Parse(strings.NewReader(tc.src), int64(len(tc.src)))
			if ok {
				t.Errorf("Parse returned true for a file with no recognised generator line; it reported %q %q with %d fields",
					got.Slicer, got.SlicerVersion, got.fields())
			}
			if got.fields() == 0 {
				t.Fatal("fixture no longer parses at all, so this test proves nothing")
			}
		})
	}
}

// TestParseReadsOnlyTwoWindows is the memory constraint, stated as a test.
//
// G-code for a large print runs to hundreds of megabytes, and the upload path
// calls Parse while holding the file open on a request goroutine. This asserts
// the exact reads: two of them, 144 KB in total, at the two ends. A test that
// only checked the parsed output would pass just as happily with an
// io.ReadAll, and the failure would arrive as an out-of-memory in production.
func TestParseReadsOnlyTwoWindows(t *testing.T) {
	raw, err := os.ReadFile("testdata/prusaslicer.gcode")
	if err != nil {
		t.Fatal(err)
	}
	want, _ := Parse(strings.NewReader(string(raw)), int64(len(raw)))

	const size = 600 << 20
	head, tail := splitAtLine(raw, HeadBytes)
	big := &spliced{size: size, segs: []segment{
		{off: 0, data: head},
		{off: size - int64(len(tail)), data: tail},
	}}

	got, ok := Parse(big, size)
	if !ok {
		t.Fatal("Parse returned false")
	}
	if a, b := jsonOf(t, got), jsonOf(t, want); a != b {
		t.Errorf("600 MB file parsed differently from the same bytes read whole:\n%s\nwant:\n%s", a, b)
	}

	if len(big.reads) != 2 {
		t.Fatalf("made %d reads, want 2: %v", len(big.reads), big.reads)
	}
	var total int64
	for _, r := range big.reads {
		total += r.n
	}
	if total != HeadBytes+TailBytes {
		t.Errorf("read %d bytes, want %d", total, HeadBytes+TailBytes)
	}
	if big.reads[0].off != 0 {
		t.Errorf("first read at %d, want 0", big.reads[0].off)
	}
	if big.reads[1].off != size-TailBytes {
		t.Errorf("second read at %d, want %d", big.reads[1].off, size-TailBytes)
	}
}

// TestParseSkipsMiddle states the cost of the two windows out loud: a setting
// that lives neither near the start nor near the end is not read. No slicer
// puts one there today, and this test exists so that if one ever does, the
// person who adds a mid-file key finds out here rather than wondering why the
// field is blank.
func TestParseSkipsMiddle(t *testing.T) {
	const size = 600 << 20
	big := &spliced{size: size, segs: []segment{
		{off: 0, data: []byte("; generated by PrusaSlicer 2.9.2 on 2025-01-01 at 00:00:00\n; layer_height = 0.2\n")},
		{off: size / 2, data: []byte("\n; temperature = 999\n")},
	}}

	got, ok := Parse(big, size)
	if !ok {
		t.Fatal("Parse returned false")
	}
	if got.LayerHeightMm == nil || *got.LayerHeightMm != 0.2 {
		t.Fatalf("layer height = %v, want 0.2", deref(got.LayerHeightMm))
	}
	if got.NozzleTempC != nil {
		t.Errorf("nozzle temp = %v, want absent: a key from the middle of the file was read", *got.NozzleTempC)
	}
}

// TestParseRejectsNonFinite keeps NaN and infinities out of Meta.
//
// json.Marshal refuses to encode either, and the caller marshals during upload,
// so a file containing one would fail the whole upload rather than merely
// producing no settings - the one outcome the product constraint forbids for a
// metadata problem. Both cases here are reachable from a real file: ParseFloat
// accepts the literal word "NaN" for a duration, and two filament totals that
// each fit in a float64 can overflow to +Inf when summed across extruders.
func TestParseRejectsNonFinite(t *testing.T) {
	huge := "17" + strings.Repeat("0", 307) // just under the float64 maximum

	for _, tc := range []struct {
		name string
		line string
	}{
		{"duration NaN", "; estimated printing time (normal mode) = NaN"},
		{"duration Inf", "; estimated printing time (normal mode) = Inf"},
		{"summed overflow", "; filament used [mm] = " + huge + ", " + huge},
		{"layer height NaN", "; layer_height = NaN"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			src := "; generated by PrusaSlicer 2.9.2 on 2025-01-01 at 00:00:00\n" +
				tc.line + "\n; perimeters = 2\n"

			got, ok := Parse(strings.NewReader(src), int64(len(src)))
			if !ok {
				t.Fatal("Parse returned false")
			}
			if got.PrintTimeSeconds != nil {
				t.Errorf("print time = %v, want absent", *got.PrintTimeSeconds)
			}
			if got.FilamentMm != nil {
				t.Errorf("filament length = %v, want absent", *got.FilamentMm)
			}
			if got.LayerHeightMm != nil {
				t.Errorf("layer height = %v, want absent", *got.LayerHeightMm)
			}
			if _, err := json.Marshal(got); err != nil {
				t.Errorf("Meta will not marshal, so the upload would fail: %v", err)
			}
		})
	}
}

// TestParseEmptyAndTiny covers the inputs the upload path really can hand us: a
// zero-byte file, and a file too short for even one window.
func TestParseEmptyAndTiny(t *testing.T) {
	if _, ok := Parse(strings.NewReader(""), 0); ok {
		t.Error("empty file returned true")
	}
	if _, ok := Parse(strings.NewReader("G1 X0\n"), 6); ok {
		t.Error("a file with no comments returned true")
	}
	src := "; generated by PrusaSlicer 2.9.2 on 2025-01-01 at 00:00:00\n"
	if _, ok := Parse(strings.NewReader(src), int64(len(src))); ok {
		t.Error("a generator line with no settings returned true; the panel would be a header and a footer")
	}
}

// TestParseDuration covers the two shapes of time a slicer writes. The bare
// number has to be checked first: read as a unit string, Cura's ";TIME:35"
// would be 35 of nothing.
func TestParseDuration(t *testing.T) {
	for _, tc := range []struct {
		in   string
		want int
		ok   bool
	}{
		{"35", 35, true},
		{"57s", 57, true},
		{"12m 5s", 725, true},
		{"1h 47m 18s", 6438, true},
		{"2d 3h 4m 5s", 183845, true},
		{"1h", 3600, true},
		{"", 0, false},
		{"unknown", 0, false},
		{"12x", 0, false},
		{"12m 5", 0, false},

		// Anything that would make int(v) undefined, or make the accumulator
		// wrap. Converting an out-of-range float to int is implementation-
		// dependent in Go, so without the bound these come back as the most
		// negative int64 and the panel renders a print that finished before it
		// started. `NaN` is here because ParseFloat spells it as a number.
		{"1e300", 0, false},
		{"-35", 0, false},
		{"NaN", 0, false},
		{"9999999999999d", 0, false},
		{"4611686018427387904d", 0, false},
		{"1000000h 1000000h 1000000h", 0, false},

		// A sign is not a separator. The loop used to skip every character it
		// did not recognise, which read `-1h` as an hour and made the panel
		// disagree with the file it came from.
		{"-1h", 0, false},
		{"1h -2m", 0, false},
		{"1h x 2m", 0, false},
	} {
		t.Run(tc.in, func(t *testing.T) {
			got, ok := parseDuration(tc.in)
			if ok != tc.ok || (ok && got != tc.want) {
				t.Errorf("parseDuration(%q) = %d, %v; want %d, %v", tc.in, got, ok, tc.want, tc.ok)
			}
		})
	}
}

// A layer count comes out of the same float64 path as every other number, and
// int(1e33) is undefined in Go. This is the whole reason count has a bound: a
// file can legitimately contain a digit run that long, and the result would be
// stored and rendered as -9223372036854775808.
func TestCountRejectsWhatDoesNotFitAnInt(t *testing.T) {
	for _, tc := range []struct {
		value string
		want  string
	}{
		{"3", "3"},
		{"0", "0"},
		{"999999999999999999999999999999999", "absent"},
		{"-1", "absent"},

		// Truncating would have reported 2 walls for a file that says 2.9, and
		// a number nothing in the file supports is worse than no number.
		{"2.9", "absent"},
	} {
		t.Run(tc.value, func(t *testing.T) {
			p := parser{seen: map[string]string{"perimeters": tc.value}}
			got := "absent"
			if n := p.count("perimeters"); n != nil {
				got = strconv.Itoa(*n)
			}
			if got != tc.want {
				t.Errorf("count(%q) = %s, want %s", tc.value, got, tc.want)
			}
		})
	}
}

// TestLeadingNumber is one function doing the work of three, so this pins the
// forms it has to swallow: a percentage, a length with a unit glued on, and a
// plain decimal.
func TestLeadingNumber(t *testing.T) {
	for _, tc := range []struct {
		in   string
		want float64
		ok   bool
	}{
		{"0.20", 0.2, true},
		{"15%", 15, true},
		{"0.00829066m", 0.00829066, true},
		{" 230 ", 230, true},
		{"-3.5", -3.5, true},
		{"1.2.3", 1.2, true},
		{"", 0, false},
		{"gyroid", 0, false},
		{"%", 0, false},
		{"NaN", 0, false},
	} {
		t.Run(tc.in, func(t *testing.T) {
			got, ok := leadingNumber(tc.in)
			if ok != tc.ok || (ok && got != tc.want) {
				t.Errorf("leadingNumber(%q) = %v, %v; want %v, %v", tc.in, got, ok, tc.want, tc.ok)
			}
		})
	}
}

func parseFile(t *testing.T, name string) (Meta, bool) {
	t.Helper()
	file, err := os.Open(name)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { file.Close() })
	st, err := file.Stat()
	if err != nil {
		t.Fatal(err)
	}
	return Parse(file, st.Size())
}

func jsonOf(t *testing.T, m Meta) string {
	t.Helper()
	b, err := json.MarshalIndent(m, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	return string(b)
}

func deref(p *float64) any {
	if p == nil {
		return "absent"
	}
	return *p
}

func derefInt(p *int) any {
	if p == nil {
		return "absent"
	}
	return *p
}

type readRec struct{ off, n int64 }

type segment struct {
	off  int64
	data []byte
}

// spliced is a file far too big to hold in memory: real bytes at chosen
// offsets, extrusion moves everywhere else, and a note of every read made.
type spliced struct {
	size  int64
	segs  []segment
	reads []readRec
}

var padding = []byte("G1 X1 Y1 E0.1\n")

func (s *spliced) ReadAt(p []byte, off int64) (int, error) {
	s.reads = append(s.reads, readRec{off, int64(len(p))})
	for i := range p {
		p[i] = padding[(off+int64(i))%int64(len(padding))]
	}
	for _, sg := range s.segs {
		start := max(off, sg.off)
		end := min(off+int64(len(p)), sg.off+int64(len(sg.data)))
		if start < end {
			copy(p[start-off:end-off], sg.data[start-sg.off:end-sg.off])
		}
	}
	return len(p), nil
}

// splitAtLine cuts a fixture into the bytes that belong at the start of a big
// file and the bytes that belong at its end, on a line boundary so that no line
// is lost to the cut. The tail keeps a leading newline: the first line of the
// tail window is always dropped as a fragment, and this gives it an empty one
// to drop.
func splitAtLine(raw []byte, at int) (head, tail []byte) {
	cut := bytes.LastIndexByte(raw[:at], '\n') + 1
	return raw[:cut], append([]byte{'\n'}, raw[cut:]...)
}

// TestParseBuildVolume covers the shapes a printer profile can declare that the
// six real fixtures do not: a delta's polygon, a bed with no height limit, and
// the malformed values a hand-edited profile can leave behind.
//
// A delta's bed_shape is a many-sided approximation of a circle, and what comes
// back for it is its bounding box - both the extent and the origin, since a
// delta's polygon is centred on zero and so runs negative. The viewer draws that
// box as the plate, which is wrong in the corners for a round bed and right
// everywhere the print actually is; a plate at the origin instead would sit
// beside the toolpaths rather than under them, which is the failure worth
// avoiding first. Drawing the polygon itself is the follow-up.
func TestParseBuildVolume(t *testing.T) {
	for _, tc := range []struct {
		name  string
		lines []string
		want  *BuildVolume
	}{
		{
			name:  "rectangle at the origin",
			lines: []string{"; bed_shape = 0x0,250x0,250x210,0x210", "; max_print_height = 217"},
			want:  &BuildVolume{MaxXMm: 250, MaxYMm: 210, HeightMm: 217},
		},
		{
			// A Prusa Mini's bed is declared with a negative origin. Reporting
			// the size alone would put the plate 8 mm from where the machine
			// coordinates in the file actually are.
			name:  "rectangle away from the origin",
			lines: []string{"; bed_shape = -2x-8,178x-8,178x172,-2x172", "; max_print_height = 180"},
			want: &BuildVolume{
				MinXMm: -2, MinYMm: -8, MaxXMm: 178, MaxYMm: 172,
				HeightMm: 180,
			},
		},
		{
			// The corners in a different order are still the same rectangle.
			name:  "rectangle listed anticlockwise",
			lines: []string{"; bed_shape = 0x210,250x210,250x0,0x0", "; max_print_height = 217"},
			want:  &BuildVolume{MaxXMm: 250, MaxYMm: 210, HeightMm: 217},
		},
		{
			name: "delta circle approximation",
			lines: []string{
				"; bed_shape = 0x-85,42x-73,73x-42,85x0,73x42,42x73,0x85,-42x73,-73x42,-85x0,-73x-42,-42x-73",
				"; max_print_height = 240",
			},
			want: &BuildVolume{
				MinXMm: -85, MinYMm: -85, MaxXMm: 85, MaxYMm: 85,
				HeightMm: 240,
			},
		},
		{
			// A parallelogram, whose bounding rectangle is wider than any of
			// its sides: the envelope has to come from the extremes, not from
			// the first and third corner.
			name:  "four points that are not a rectangle",
			lines: []string{"; bed_shape = 0x0,100x0,120x100,20x100", "; max_print_height = 200"},
			want: &BuildVolume{
				MinXMm: 0, MinYMm: 0, MaxXMm: 120, MaxYMm: 100,
				HeightMm: 200,
			},
		},
		{
			name:  "orca spelling wins over the slic3r one it also writes",
			lines: []string{"; printable_area = 0x0,250x0,250x250,0x250", "; printable_height = 250", "; bed_shape = 0x0,180x0,180x180,0x180"},
			want:  &BuildVolume{MaxXMm: 250, MaxYMm: 250, HeightMm: 250},
		},
		{
			// The trap orcaslicer_2.3.gcode really contains: a different key
			// that starts with the same word, written before the real one and
			// set to zero.
			name: "a zero on a lookalike key does not become the height",
			lines: []string{
				"; extruder_printable_height = 0",
				"; printable_area = 0x0,250x0,250x250,0x250",
				"; printable_height = 250",
			},
			want: &BuildVolume{MaxXMm: 250, MaxYMm: 250, HeightMm: 250},
		},
		{name: "bed with no height", lines: []string{"; bed_shape = 0x0,250x0,250x210,0x210"}},
		{name: "height with no bed", lines: []string{"; max_print_height = 217"}},
		{
			name:  "zero height",
			lines: []string{"; bed_shape = 0x0,250x0,250x210,0x210", "; max_print_height = 0"},
		},
		{
			name:  "bed with no area",
			lines: []string{"; bed_shape = 5x5,5x5,5x5,5x5", "; max_print_height = 200"},
		},
		{
			name:  "two points is not a polygon",
			lines: []string{"; bed_shape = 0x0,250x210", "; max_print_height = 217"},
		},
		{
			name:  "a point with no separator",
			lines: []string{"; bed_shape = 0x0,250,250x210,0x210", "; max_print_height = 217"},
		},
		{
			name:  "a point that is not a number",
			lines: []string{"; bed_shape = 0x0,250x0,widthxheight,0x210", "; max_print_height = 217"},
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			got := parseLines(t, tc.lines)
			if a, b := jsonOf(t, Meta{BuildVolume: got.BuildVolume}), jsonOf(t, Meta{BuildVolume: tc.want}); a != b {
				t.Errorf("build volume:\n%s\nwant:\n%s", a, b)
			}
		})
	}
}

// TestParseFilamentColor is what AC3 rests on: the viewer draws the toolpaths
// in this colour and does not check it again, so anything that is not a colour
// has to be absent rather than passed through as a string three.js will read as
// black.
func TestParseFilamentColor(t *testing.T) {
	for _, tc := range []struct{ name, line, want string }{
		{name: "six digits", line: "; filament_colour = #F2754E", want: "#f2754e"},
		{
			// The five-extruder case, which needs no code: line() already cuts
			// an `=` value at the first `;`.
			name: "the first of a per-extruder list",
			line: "; filament_colour = #FF8000;#00AE42;#FFFFFF;#000000;#26A69A",
			want: "#ff8000",
		},
		{
			// No G-code fixture writes the alpha form, but dropping a colour
			// that is sitting right there is the worse of the two failures.
			name: "eight digits keeps the six that mean something",
			line: "; filament_colour = #00AE42FF",
			want: "#00ae42",
		},
		{
			// A longer value has to be dropped rather than cut down to its
			// first seven characters, which would report a colour nobody wrote.
			name: "ten digits",
			line: "; filament_colour = #F2754EFF00",
		},
		{name: "empty", line: "; filament_colour = "},
		{name: "the empty lookalike key", line: `; default_filament_colour = ""`},
		{name: "quoted", line: `; filament_colour = "#F2754E"`},
		{name: "no hash", line: "; filament_colour = F2754E"},
		{name: "three-digit shorthand", line: "; filament_colour = #F00"},
		{name: "a name rather than a value", line: "; filament_colour = orange"},
		{name: "not hex", line: "; filament_colour = #GGGGGG"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			if got := parseLines(t, []string{tc.line}).FilamentColor; got != tc.want {
				t.Errorf("colour = %q, want %q", got, tc.want)
			}
		})
	}
}

// parseLines runs Parse over a PrusaSlicer file made of the given config lines.
//
// The generator line is what makes Parse recognise the file at all, and the
// layer height is there because Parse reports nothing at all from a file with
// no panel field in it. A build volume without a layer height beside it is not
// a file any slicer writes - both sit in the same alphabetical config block -
// so the gate stays counting panel rows only.
func parseLines(t *testing.T, lines []string) Meta {
	t.Helper()
	src := "; generated by PrusaSlicer 2.9.2 on 2025-01-01 at 00:00:00\n" +
		"; layer_height = 0.2\n" +
		strings.Join(lines, "\n") + "\n"
	got, ok := Parse(strings.NewReader(src), int64(len(src)))
	if !ok {
		t.Fatal("Parse returned false")
	}
	return got
}
