; HEADER_BLOCK_START
; generated by BambuStudio-02.07.01.62 on 2025-06-14 at 09:12:33
; model printing time: 42m 3s; total estimated time: 47m 18s
; total layer number: 118
; total filament length [mm] : 12250.44
; total filament volume [cm^3] : 29.47
; total filament weight [g] : 36.71
; filament_density: 1.24
; filament_diameter: 1.75
; HEADER_BLOCK_END

; CONFIG_BLOCK_START
; bottom_shell_layers = 3
; curr_bed_type = Textured PEI Plate
; enable_support = 1
; filament_cost = 24.99
; filament_max_volumetric_speed = 21
; filament_settings_id = "Bambu PLA Basic @BBL X1C"
; filament_type = PLA;PLA
; first_layer_bed_temperature = 60
; layer_height = 0.2
; nozzle_diameter = 0.4
; nozzle_temperature = 220
; printer_model = Bambu Lab X1 Carbon
; sparse_infill_density = 15%
; sparse_infill_pattern = gyroid
; top_shell_layers = 5
; wall_loops = 3
; CONFIG_BLOCK_END

; ---- body elided for the test fixture ----

M400
; EXECUTABLE_BLOCK_END
